from pydantic import Field

from .base import BaseType


class RealizationSalesReport(BaseType):
    realizationreport_id: int | None = Field(None, alias="realizationreport_id")
    date_from: str | None = Field(None, alias="date_from")
    date_to: str | None = Field(None, alias="date_to")
    create_dt: str | None = Field(None, alias="create_dt")
    currency_name: str | None = Field(None, alias="currency_name")
    suppliercontract_code: str | None = Field(None, alias="suppliercontract_code")
    rrd_id: int | None = Field(None, alias="rrd_id")
    gi_id: int | None = Field(None, alias="gi_id")
    dlv_prc: float | None = Field(None, alias="dlv_prc")
    fix_tariff_date_from: str | None = Field(None, alias="fix_tariff_date_from")
    fix_tariff_date_to: str | None = Field(None, alias="fix_tariff_date_to")
    subject_name: str | None = Field(None, alias="subject_name")
    nm_id: int | None = Field(None, alias="nm_id")
    brand_name: str | None = Field(None, alias="brand_name")
    sa_name: str | None = Field(None, alias="sa_name")
    ts_name: str | None = Field(None, alias="ts_name")
    barcode: str | None = Field(None, alias="barcode")
    doc_type_name: str | None = Field(None, alias="doc_type_name")
    quantity: int | None = Field(None, alias="quantity")
    retail_price: float | None = Field(None, alias="retail_price")
    retail_amount: float | None = Field(None, alias="retail_amount")
    sale_percent: float | None = Field(None, alias="sale_percent")
    commission_percent: float | None = Field(None, alias="commission_percent")
    office_name: str | None = Field(None, alias="office_name")
    supplier_oper_name: str | None = Field(None, alias="supplier_oper_name")
    order_dt: str | None = Field(None, alias="order_dt")
    sale_dt: str | None = Field(None, alias="sale_dt")
    rr_dt: str | None = Field(None, alias="rr_dt")
    shk_id: int | None = Field(None, alias="shk_id")
    retail_price_withdisc_rub: float | None = Field(None, alias="retail_price_withdisc_rub")
    delivery_amount: int | None = Field(None, alias="delivery_amount")
    return_amount: int | None = Field(None, alias="return_amount")
    delivery_rub: float | None = Field(None, alias="delivery_rub")
    gi_box_type_name: str | None = Field(None, alias="gi_box_type_name")
    product_discount_for_report: float | None = Field(None, alias="product_discount_for_report")
    supplier_promo: float | None = Field(None, alias="supplier_promo")
    ppvz_spp_prc: float | None = Field(None, alias="ppvz_spp_prc")
    ppvz_kvw_prc_base: float | None = Field(None, alias="ppvz_kvw_prc_base")
    ppvz_kvw_prc: float | None = Field(None, alias="ppvz_kvw_prc")
    sup_rating_prc_up: float | None = Field(None, alias="sup_rating_prc_up")
    is_kgvp_v2: float | None = Field(None, alias="is_kgvp_v2")
    ppvz_sales_commission: float | None = Field(None, alias="ppvz_sales_commission")
    ppvz_for_pay: float | None = Field(None, alias="ppvz_for_pay")
    ppvz_reward: float | None = Field(None, alias="ppvz_reward")
    acquiring_fee: float | None = Field(None, alias="acquiring_fee")
    acquiring_percent: float | None = Field(None, alias="acquiring_percent")
    payment_processing: str | None = Field(None, alias="payment_processing")
    acquiring_bank: str | None = Field(None, alias="acquiring_bank")
    ppvz_vw: float | None = Field(None, alias="ppvz_vw")
    ppvz_vw_nds: float | None = Field(None, alias="ppvz_vw_nds")
    ppvz_office_name: str | None = Field(None, alias="ppvz_office_name")
    ppvz_office_id: int | None = Field(None, alias="ppvz_office_id")
    ppvz_supplier_id: int | None = Field(None, alias="ppvz_supplier_id")
    ppvz_supplier_name: str | None = Field(None, alias="ppvz_supplier_name")
    ppvz_inn: str | None = Field(None, alias="ppvz_inn")
    declaration_number: str | None = Field(None, alias="declaration_number")
    bonus_type_name: str | None = Field(None, alias="bonus_type_name")
    sticker_id: str | None = Field(None, alias="sticker_id")
    site_country: str | None = Field(None, alias="site_country")
    srv_dbs: bool | None = Field(None, alias="srv_dbs")
    penalty: float | None = Field(None, alias="penalty")
    additional_payment: float | None = Field(None, alias="additional_payment")
    rebill_logistic_cost: float | None = Field(None, alias="rebill_logistic_cost")
    rebill_logistic_org: str | None = Field(None, alias="rebill_logistic_org")
    storage_fee: float | None = Field(None, alias="storage_fee")
    deduction: float | None = Field(None, alias="deduction")
    acceptance: float | None = Field(None, alias="acceptance")
    assembly_id: int | None = Field(None, alias="assembly_id")
    kiz: str | None = Field(None, alias="kiz")
    srid: str | None = Field(None, alias="srid")
    report_type: int | None = Field(None, alias="report_type")
    is_legal_entity: bool | None = Field(None, alias="is_legal_entity")
    trbx_id: str | None = Field(None, alias="trbx_id")
    installment_cofinancing_amount: float | None = Field(
        None, alias="installment_cofinancing_amount"
    )
    wibes_wb_discount_percent: float | None = Field(None, alias="wibes_wb_discount_percent")
    cashback_amount: float | None = Field(None, alias="cashback_amount")
    cashback_discount: float | None = Field(None, alias="cashback_discount")
    cashback_commission_change: float | None = Field(None, alias="cashback_commission_change")
    order_uid: str | None = Field(None, alias="order_uid")
    payment_schedule: int | None = Field(None, alias="payment_schedule")
    delivery_method: str | None = Field(None, alias="delivery_method")
    seller_promo_id: int | None = Field(None, alias="seller_promo_id")
    seller_promo_discount: float | None = Field(None, alias="seller_promo_discount")
    loyalty_id: int | None = Field(None, alias="loyalty_id")
    loyalty_discount: float | None = Field(None, alias="loyalty_discount")
    uuid_promocode: str | None = Field(None, alias="uuid_promocode")
    sale_price_promocode_discount_prc: float | None = Field(
        None, alias="sale_price_promocode_discount_prc"
    )
