from enum import StrEnum


class SalesFunnelOrderField(StrEnum):
    OPEN_CARD = "openCard"
    ADD_TO_CART = "addToCart"
    ORDER_COUNT = "orderCount"
    ORDER_SUM = "orderSum"
    BUYOUT_COUNT = "buyoutCount"
    BUYOUT_SUM = "buyoutSum"
    CANCEL_COUNT = "cancelCount"
    CANCEL_SUM = "cancelSum"
    AVG_PRICE = "avgPrice"
    STOCK_MP_QTY = "stockMpQty"
    STOCK_WB_QTY = "stockWbQty"
    SHARE_ORDER_PERCENT = "shareOrderPercent"
    ADD_TO_WISHLIST = "addToWishlist"
    TIME_TO_READY = "timeToReady"
    LOCALIZATION_PERCENT = "localizationPercent"
    WB_CLUB_ORDER_COUNT = "wbClub.orderCount"
    WB_CLUB_ORDER_SUM = "wbClub.orderSum"
    WB_CLUB_BUYOUT_SUM = "wbClub.buyoutSum"
    WB_CLUB_BUYOUT_COUNT = "wbClub.buyoutCount"
    WB_CLUB_CANCEL_SUM = "wbClub.cancelSum"
    WB_CLUB_AVG_PRICE = "wbClub.avgPrice"
    WB_CLUB_BUYOUT_PERCENT = "wbClub.buyoutPercent"
    WB_CLUB_AVG_ORDER_COUNT_PER_DAY = "wbClub.avgOrderCountPerDay"
    WB_CLUB_CANCEL_COUNT = "wbClub.cancelCount"
