# @generated
# This file was auto-generated by scripts/codegen.py from specs/. Do not edit by hand.

from __future__ import annotations

from typing import Any

from msgspec import field as _field

from ..client.model import WBModel


class BrandsResponse(WBModel):
    brands: list[BrandsResponseBrandsItem] | None = _field(default=None)
    next: int | None = _field(default=None)
    """Параметр пагинации. Укажите это значение в запросе, чтобы получить следующий пакет данных.
    Если поле отсутствует, вы получили все данные
    """
    total: int | None = _field(default=None)
    """Общее количество брендов предмета"""


class BrandsResponseBrandsItem(WBModel):
    id: int | None = _field(default=None)
    """ID бренда"""
    logo_url: str | None = _field(default=None, name="logoUrl")
    """URL логотипа бренда"""
    name: str | None = _field(default=None)
    """Название бренда"""


class CreateBarcodeBody(WBModel):
    count: int | None = _field(default=None)
    """Кол-во баркодов которые надо сгенерировать, максимальное доступное количество баркодов для
    генерации - `5 000`
    """


class CreateBarcodeResponse(WBModel):
    additional_errors: str | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: list[str] | None = _field(default=None)
    """Массив сгенерированных баркодов"""
    error: bool | None = _field(default=None)
    """Флаг ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class CreateCardsUploadAddBody(WBModel):
    cards_to_add: list[CreateCardsUploadAddBodyCardsToAddItem] | None = _field(
        default=None, name="cardsToAdd"
    )
    """Добавляемые карточки товаров"""
    imt_id: int | None = _field(default=None, name="imtID")
    """`imtID` отдельной карточки товара или группы объединённых карточек товаров, к которой
    присоединяются создаваемые карточки
    """


class CreateCardsUploadAddBodyCardsToAddItem(WBModel):
    brand: str | None = _field(default=None)
    """Бренд"""
    characteristics: list[CreateCardsUploadAddBodyCardsToAddItemCharacteristicsItem] | None = _field(
        default=None
    )
    """Характеристики товара.  Можно получить методом Характеристики предмета"""
    description: str | None = _field(default=None)
    """Описание товара. Максимальное количество символов зависит от категории товара Стандарт —
    2000, минимум — 1000, максимум — 5000 …
    """
    dimensions: CreateCardsUploadAddBodyCardsToAddItemDimensions | None = _field(default=None)
    """Габариты и вес товара **c упаковкой**. Укажите в `сантиметрах` и `килограммах` для любого
    товара. …
    """
    kiz_marked: bool | None = _field(default=None, name="kizMarked")
    """Подтверждение, что на товар нанесён обязательный код маркировки Честного знака: …"""
    sizes: list[CreateCardsUploadAddBodyCardsToAddItemSizesItem] | None = _field(default=None)
    """Массив размеров. Если не указать для размерного товара (обувь, одежда и др.), сгенерируется
    автоматически с `techSize` = "A", `wbSize` = "1" и баркодом
    """
    title: str | None = _field(default=None)
    """Наименование товара"""
    vendor_code: str | None = _field(default=None, name="vendorCode")
    """Артикул продавца"""
    wholesale: CreateCardsUploadAddBodyCardsToAddItemWholesale | None = _field(default=None)
    """Оптовая продажа"""


class CreateCardsUploadAddBodyCardsToAddItemCharacteristicsItem(WBModel):
    id: int | None = _field(default=None)
    """ID характеристики"""
    value: Any | None = _field(default=None)
    """Значения характеристики.  Тип данных — массив строк или число — зависит от типа
    характеристики, см. описание поля `charcType` в методе Характеристики предмета. …
    """


class CreateCardsUploadAddBodyCardsToAddItemDimensions(WBModel):
    """Габариты и вес товара **c упаковкой**.<br>"""

    height: int | None = _field(default=None)
    """Высота, см"""
    length: int | None = _field(default=None)
    """Длина, см"""
    weight_brutto: float | None = _field(default=None, name="weightBrutto")
    """Вес, кгКоличество знаков после запятой <=3"""
    width: int | None = _field(default=None)
    """Ширина, см"""


class CreateCardsUploadAddBodyCardsToAddItemSizesItem(WBModel):
    price: int | None = _field(default=None)
    """Цена товара"""
    skus: list[str] | None = _field(default=None)
    """Баркод. Если не указать, сгенерируется автоматически"""
    tech_size: str | None = _field(default=None, name="techSize")
    """Размер товара (например, XL, 45)"""
    wb_size: str | None = _field(default=None, name="wbSize")
    """Российский размер товара"""


class CreateCardsUploadAddBodyCardsToAddItemWholesale(WBModel):
    """Оптовая продажа"""

    enabled: bool | None = _field(default=None)
    """Предназначена ли карточка товара для оптовой продажи"""
    quantum: float | None = _field(default=None)
    """Количество единиц товара в упаковке"""


class CreateCardsUploadAddCardsToAddItem(WBModel):
    brand: str | None = _field(default=None)
    """Бренд"""
    characteristics: list[CreateCardsUploadAddCardsToAddItemCharacteristicsItem] | None = _field(default=None)
    """Характеристики товара.  Можно получить методом Характеристики предмета"""
    description: str | None = _field(default=None)
    """Описание товара. Максимальное количество символов зависит от категории товара Стандарт —
    2000, минимум — 1000, максимум — 5000 …
    """
    dimensions: CreateCardsUploadAddCardsToAddItemDimensions | None = _field(default=None)
    """Габариты и вес товара **c упаковкой**. Укажите в `сантиметрах` и `килограммах` для любого
    товара. …
    """
    kiz_marked: bool | None = _field(default=None, name="kizMarked")
    """Подтверждение, что на товар нанесён обязательный код маркировки Честного знака: …"""
    sizes: list[CreateCardsUploadAddCardsToAddItemSizesItem] | None = _field(default=None)
    """Массив размеров. Если не указать для размерного товара (обувь, одежда и др.), сгенерируется
    автоматически с `techSize` = "A", `wbSize` = "1" и баркодом
    """
    title: str | None = _field(default=None)
    """Наименование товара"""
    vendor_code: str | None = _field(default=None, name="vendorCode")
    """Артикул продавца"""
    wholesale: CreateCardsUploadAddCardsToAddItemWholesale | None = _field(default=None)
    """Оптовая продажа"""


class CreateCardsUploadAddCardsToAddItemCharacteristicsItem(WBModel):
    id: int | None = _field(default=None)
    """ID характеристики"""
    value: Any | None = _field(default=None)
    """Значения характеристики.  Тип данных — массив строк или число — зависит от типа
    характеристики, см. описание поля `charcType` в методе Характеристики предмета. …
    """


class CreateCardsUploadAddCardsToAddItemDimensions(WBModel):
    """Габариты и вес товара **c упаковкой**.<br>"""

    height: int | None = _field(default=None)
    """Высота, см"""
    length: int | None = _field(default=None)
    """Длина, см"""
    weight_brutto: float | None = _field(default=None, name="weightBrutto")
    """Вес, кгКоличество знаков после запятой <=3"""
    width: int | None = _field(default=None)
    """Ширина, см"""


class CreateCardsUploadAddCardsToAddItemSizesItem(WBModel):
    price: int | None = _field(default=None)
    """Цена товара"""
    skus: list[str] | None = _field(default=None)
    """Баркод. Если не указать, сгенерируется автоматически"""
    tech_size: str | None = _field(default=None, name="techSize")
    """Размер товара (например, XL, 45)"""
    wb_size: str | None = _field(default=None, name="wbSize")
    """Российский размер товара"""


class CreateCardsUploadAddCardsToAddItemWholesale(WBModel):
    """Оптовая продажа"""

    enabled: bool | None = _field(default=None)
    """Предназначена ли карточка товара для оптовой продажи"""
    quantum: float | None = _field(default=None)
    """Количество единиц товара в упаковке"""


class CreateCardsUploadBodyItem(WBModel):
    subject_id: int | None = _field(default=None, name="subjectID")
    """ID предмета"""
    variants: list[CreateCardsUploadBodyItemVariantsItem] | None = _field(default=None)
    """Объединённые карточки товаров.Чтобы создать отдельную карточку, передайте только один объект
    """


class CreateCardsUploadBodyItemVariantsItem(WBModel):
    brand: str | None = _field(default=None)
    """Бренд"""
    characteristics: list[CreateCardsUploadBodyItemVariantsItemCharacteristicsItem] | None = _field(
        default=None
    )
    """Характеристики товара.  Можно получить методом Характеристики предмета"""
    description: str | None = _field(default=None)
    """Описание товара. Максимальное количество символов зависит от категории товара Стандарт —
    2000, минимум — 1000, максимум — 5000 …
    """
    dimensions: CreateCardsUploadBodyItemVariantsItemDimensions | None = _field(default=None)
    """Габариты и вес товара **c упаковкой**. Укажите в `сантиметрах` и `килограммах` для любого
    товара. …
    """
    kiz_marked: bool | None = _field(default=None, name="kizMarked")
    """Подтверждение, что на товар нанесён обязательный код маркировки Честного знака: …"""
    sizes: list[CreateCardsUploadBodyItemVariantsItemSizesItem] | None = _field(default=None)
    """Массив размеров. Если не указать для размерного товара (обувь, одежда и др.), сгенерируется
    автоматически с `techSize` = "A", `wbSize` = "1" и баркодом
    """
    title: str | None = _field(default=None)
    """Наименование товара"""
    vendor_code: str | None = _field(default=None, name="vendorCode")
    """Артикул продавца"""
    wholesale: CreateCardsUploadBodyItemVariantsItemWholesale | None = _field(default=None)
    """Оптовая продажа"""


class CreateCardsUploadBodyItemVariantsItemCharacteristicsItem(WBModel):
    id: int | None = _field(default=None)
    """ID характеристики"""
    value: Any | None = _field(default=None)
    """Значения характеристики.  Тип данных — массив строк или число — зависит от типа
    характеристики, см. описание поля `charcType` в методе Характеристики предмета. …
    """


class CreateCardsUploadBodyItemVariantsItemDimensions(WBModel):
    """Габариты и вес товара **c упаковкой**.<br>"""

    height: int | None = _field(default=None)
    """Высота, см"""
    length: int | None = _field(default=None)
    """Длина, см"""
    weight_brutto: float | None = _field(default=None, name="weightBrutto")
    """Вес, кгКоличество знаков после запятой <=3"""
    width: int | None = _field(default=None)
    """Ширина, см"""


class CreateCardsUploadBodyItemVariantsItemSizesItem(WBModel):
    price: int | None = _field(default=None)
    """Цена товара"""
    skus: list[str] | None = _field(default=None)
    """Массив баркодов для размера. Если не указать, сгенерируется автоматически. …"""
    tech_size: str | None = _field(default=None, name="techSize")
    """Размер товара (например, XL, 45)"""
    wb_size: str | None = _field(default=None, name="wbSize")
    """Российский размер товара"""


class CreateCardsUploadBodyItemVariantsItemWholesale(WBModel):
    """Оптовая продажа"""

    enabled: bool | None = _field(default=None)
    """Предназначена ли карточка товара для оптовой продажи"""
    quantum: float | None = _field(default=None)
    """Количество единиц товара в упаковке"""


class CreateTagBody(WBModel):
    color: str | None = _field(default=None)
    """Цвет ярлыка.  Доступные цвета:   - `D1CFD7` — серый   - `FEE0E0` — красный   - `ECDAFF` —
    фиолетовый   - `E4EAFF` — синий   - `DEF1DD` — зеленый …
    """
    name: str | None = _field(default=None)
    """Имя ярлыка"""


class CreateTagNomenclatureLinkBody(WBModel):
    nm_id: int | None = _field(default=None, name="nmID")
    """Артикул WB"""
    tags_ids: list[int] | None = _field(default=None, name="tagsIDs")
    """Массив числовых ID ярлыков. Что бы снять ярлыки с карточки товара, необходимо передать
    пустой массив. …
    """


class CreateWarehouseBody(WBModel):
    name: str | None = _field(default=None)
    """Имя склада продавца"""
    office_id: int | None = _field(default=None, name="officeId")
    """ID склада WB.Нельзя привязывать склад WB, который уже используется"""


class CreateWarehouseResponse(WBModel):
    id: int | None = _field(default=None)
    """ID склада продавца"""


class DeleteStockBody(WBModel):
    chrt_ids: list[int] | None = _field(default=None, name="chrtIds")
    """Массив ID размеров товаров"""


class GetCardsLimitsResponse(WBModel):
    additional_errors: str | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: GetCardsLimitsResponseData | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Флаг ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetCardsLimitsResponseData(WBModel):
    free_limits: int | None = _field(default=None, name="freeLimits")
    """Количество бесплатных лимитов"""
    paid_limits: int | None = _field(default=None, name="paidLimits")
    """Количество оплаченных лимитов"""


class GetCardsListBody(WBModel):
    settings: GetCardsListBodySettings | None = _field(default=None)
    """Настройки"""


class GetCardsListBodySettings(WBModel):
    """Настройки"""

    cursor: GetCardsListBodySettingsCursor | None = _field(default=None)
    """Курсор"""
    filter: GetCardsListBodySettingsFilter | None = _field(default=None)
    """Параметры фильтрации"""
    sort: GetCardsListBodySettingsSort | None = _field(default=None)
    """Параметр сортировки"""


class GetCardsListBodySettingsCursor(WBModel):
    """Курсор"""

    limit: int | None = _field(default=None)
    """Сколько карточек товаров выдать в ответе"""
    nm_id: int | None = _field(default=None, name="nmID")
    """Артикул WB, с которого надо запрашивать следующий список карточек товаров"""
    updated_at: str | None = _field(default=None, name="updatedAt")
    """Дата и время изменения"""


class GetCardsListBodySettingsFilter(WBModel):
    """Параметры фильтрации"""

    allowed_categories_only: bool | None = _field(default=None, name="allowedCategoriesOnly")
    """Фильтр по категории:   - `true` — только разрешённые   - `false` — все    Не используется
    в песочнице
    """
    brands: list[str] | None = _field(default=None)
    """Поиск по брендам"""
    imt_id: int | None = _field(default=None, name="imtID")
    """Поиск по ID для объединённых карточек товаров"""
    object_ids: list[int] | None = _field(default=None, name="objectIDs")
    """Поиск по ID предметов"""
    tag_ids: list[int] | None = _field(default=None, name="tagIDs")
    """Поиск по ID ярлыков"""
    text_search: str | None = _field(default=None, name="textSearch")
    """Поиск по артикулу продавца, артикулу WB, баркоду"""
    with_photo: int | None = _field(default=None, name="withPhoto")
    """Фильтр по фото:   * `-1` — любые карточки товаров   * `0` — только карточки без фото. С 16
    июня — любые карточки товаров   * `1` — только карточки с фото …
    """


class GetCardsListBodySettingsSort(WBModel):
    """Параметр сортировки"""

    ascending: bool | None = _field(default=None)
    """Сортировать по полю `updatedAt`:   - `false` — по убыванию   -  `true` — по возрастанию
    """


class GetCardsListResponse(WBModel):
    cards: list[GetCardsListResponseCardsItem] | None = _field(default=None)
    """Список карточек товаров"""
    cursor: GetCardsListResponseCursor | None = _field(default=None)
    """Пагинатор"""


class GetCardsListResponseCardsItem(WBModel):
    brand: str | None = _field(default=None)
    """Бренд"""
    characteristics: list[GetCardsListResponseCardsItemCharacteristicsItem] | None = _field(default=None)
    """Характеристики"""
    created_at: str | None = _field(default=None, name="createdAt")
    """Дата и время создания"""
    description: str | None = _field(default=None)
    """Описание товара"""
    dimensions: GetCardsListResponseCardsItemDimensions | None = _field(default=None)
    """Габариты и вес товара c упаковкой, см и кг"""
    imt_id: int | None = _field(default=None, name="imtID")
    """ID для объединённых карточек товаров.Един для всех артикулов WB группы объединённых
    карточек.У каждой карточки товара есть `imtID`, даже если она не объединена …
    """
    kiz_marked: bool | None = _field(default=None, name="kizMarked")
    """Есть ли подтверждение от продавца, что обязательный код маркировки Честного знака нанесён на
    товар:   - `true` — да   - `false` — нет …
    """
    need_kiz: bool | None = _field(default=None, name="needKiz")
    """Требуется ли код маркировки Честного знака для этого товара:   - `false` — не требуется   -
    `true` — требуется
    """
    nm_id: int | None = _field(default=None, name="nmID")
    """Артикул WB"""
    nm_uuid: str | None = _field(default=None, name="nmUUID")
    """Внутренний технический ID карточки товара"""
    photos: list[GetCardsListResponseCardsItemPhotosItem] | None = _field(default=None)
    """Массив фото"""
    sizes: list[GetCardsListResponseCardsItemSizesItem] | None = _field(default=None)
    """Размеры товара"""
    subject_id: int | None = _field(default=None, name="subjectID")
    """ID предмета"""
    subject_name: str | None = _field(default=None, name="subjectName")
    """Название предмета"""
    tags: list[GetCardsListResponseCardsItemTagsItem] | None = _field(default=None)
    """Ярлыки"""
    title: str | None = _field(default=None)
    """Наименование товара"""
    updated_at: str | None = _field(default=None, name="updatedAt")
    """Дата и время изменения"""
    vendor_code: str | None = _field(default=None, name="vendorCode")
    """Артикул продавца"""
    video: str | None = _field(default=None)
    """URL видео"""
    wholesale: GetCardsListResponseCardsItemWholesale | None = _field(default=None)
    """Оптовая продажа"""


class GetCardsListResponseCardsItemCharacteristicsItem(WBModel):
    id: int | None = _field(default=None)
    """ID характеристики"""
    name: str | None = _field(default=None)
    """Название характеристики"""
    value: Any | None = _field(default=None)
    """Значение характеристики. Тип значения зависит от типа характеристики"""


class GetCardsListResponseCardsItemDimensions(WBModel):
    """Габариты и вес товара c упаковкой, см и кг"""

    height: int | None = _field(default=None)
    """Высота, см"""
    is_valid: bool | None = _field(default=None, name="isValid")
    """Потенциальная некорректность габаритов товара: …"""
    length: int | None = _field(default=None)
    """Длина, см"""
    weight_brutto: float | None = _field(default=None, name="weightBrutto")
    """Вес, кгКоличество знаков после запятой <=3"""
    width: int | None = _field(default=None)
    """Ширина, см"""


class GetCardsListResponseCardsItemPhotosItem(WBModel):
    big: str | None = _field(default=None)
    """URL фото `900x1200`"""
    c246x328: str | None = _field(default=None)
    """URL фото `248x328`"""
    c516x688: str | None = _field(default=None)
    """URL фото `516x688`"""
    square: str | None = _field(default=None)
    """URL фото `600x600`"""
    tm: str | None = _field(default=None)
    """URL фото `75x100`"""


class GetCardsListResponseCardsItemSizesItem(WBModel):
    chrt_id: int | None = _field(default=None, name="chrtID")
    """Числовой ID размера для данного артикула WB"""
    skus: list[str] | None = _field(default=None)
    """Баркод товара"""
    tech_size: str | None = _field(default=None, name="techSize")
    """Размер товара (А, XXL, 57 и др.)"""
    wb_size: str | None = _field(default=None, name="wbSize")
    """Российский размер товара"""


class GetCardsListResponseCardsItemTagsItem(WBModel):
    color: str | None = _field(default=None)
    """Цвет ярлыка. Доступные цвета: - `D1CFD7` — серый - `FEE0E0` — красный - `ECDAFF` —
    фиолетовый - `E4EAFF` — синий - `DEF1DD` — зеленый - `FFECC7` — желтый
    """
    id: int | None = _field(default=None)
    """ID ярлыка"""
    name: str | None = _field(default=None)
    """Название ярлыка"""


class GetCardsListResponseCardsItemWholesale(WBModel):
    """Оптовая продажа"""

    enabled: bool | None = _field(default=None)
    """Предназначена ли карточка товара для оптовой продажи"""
    quantum: float | None = _field(default=None)
    """Количество единиц товара в упаковке"""


class GetCardsListResponseCursor(WBModel):
    """Пагинатор"""

    nm_id: int | None = _field(default=None, name="nmID")
    """Артикул WB, с которого надо запрашивать следующий список карточек товаров"""
    total: int | None = _field(default=None)
    """Количество возвращённых карточек товаров"""
    updated_at: str | None = _field(default=None, name="updatedAt")
    """Дата и время, с которых надо запрашивать следующий список карточек товаров"""


class GetCardsListSettings(WBModel):
    """Настройки"""

    cursor: GetCardsListSettingsCursor | None = _field(default=None)
    """Курсор"""
    filter: GetCardsListSettingsFilter | None = _field(default=None)
    """Параметры фильтрации"""
    sort: GetCardsListSettingsSort | None = _field(default=None)
    """Параметр сортировки"""


class GetCardsListSettingsCursor(WBModel):
    """Курсор"""

    limit: int | None = _field(default=None)
    """Сколько карточек товаров выдать в ответе"""
    nm_id: int | None = _field(default=None, name="nmID")
    """Артикул WB, с которого надо запрашивать следующий список карточек товаров"""
    updated_at: str | None = _field(default=None, name="updatedAt")
    """Дата и время изменения"""


class GetCardsListSettingsFilter(WBModel):
    """Параметры фильтрации"""

    allowed_categories_only: bool | None = _field(default=None, name="allowedCategoriesOnly")
    """Фильтр по категории:   - `true` — только разрешённые   - `false` — все    Не используется
    в песочнице
    """
    brands: list[str] | None = _field(default=None)
    """Поиск по брендам"""
    imt_id: int | None = _field(default=None, name="imtID")
    """Поиск по ID для объединённых карточек товаров"""
    object_ids: list[int] | None = _field(default=None, name="objectIDs")
    """Поиск по ID предметов"""
    tag_ids: list[int] | None = _field(default=None, name="tagIDs")
    """Поиск по ID ярлыков"""
    text_search: str | None = _field(default=None, name="textSearch")
    """Поиск по артикулу продавца, артикулу WB, баркоду"""
    with_photo: int | None = _field(default=None, name="withPhoto")
    """Фильтр по фото:   * `-1` — любые карточки товаров   * `0` — только карточки без фото. С 16
    июня — любые карточки товаров   * `1` — только карточки с фото …
    """


class GetCardsListSettingsSort(WBModel):
    """Параметр сортировки"""

    ascending: bool | None = _field(default=None)
    """Сортировать по полю `updatedAt`:   - `false` — по убыванию   -  `true` — по возрастанию
    """


class GetCardsTrashBody(WBModel):
    settings: GetCardsTrashBodySettings | None = _field(default=None)
    """Настройки"""


class GetCardsTrashBodySettings(WBModel):
    """Настройки"""

    cursor: GetCardsTrashBodySettingsCursor | None = _field(default=None)
    """Пагинатор"""
    filter: GetCardsTrashBodySettingsFilter | None = _field(default=None)
    """Параметры фильтрации"""
    sort: GetCardsTrashBodySettingsSort | None = _field(default=None)
    """Параметр сортировки"""


class GetCardsTrashBodySettingsCursor(WBModel):
    """Пагинатор"""

    limit: int | None = _field(default=None)
    """Сколько карточек товаров выдать в ответе"""
    nm_id: int | None = _field(default=None, name="nmID")
    """Артикул WB, с которого надо запрашивать следующий список карточек товаров"""
    trashed_at: str | None = _field(default=None, name="trashedAt")
    """Дата и время помещения в корзину"""


class GetCardsTrashBodySettingsFilter(WBModel):
    """Параметры фильтрации"""

    text_search: str | None = _field(default=None, name="textSearch")
    """Поиск по артикулу продавца, артикулу WB, баркоду"""


class GetCardsTrashBodySettingsSort(WBModel):
    """Параметр сортировки"""

    ascending: bool | None = _field(default=None)
    """Сортировать по `trashedAt`:   - `false` — по убыванию   - `true` — по возрастанию"""


class GetCardsTrashResponse(WBModel):
    cards: list[GetCardsTrashResponseCardsItem] | None = _field(default=None)
    """Массив карточек товаров"""
    cursor: GetCardsTrashResponseCursor | None = _field(default=None)
    """Пагинатор"""


class GetCardsTrashResponseCardsItem(WBModel):
    characteristics: list[GetCardsTrashResponseCardsItemCharacteristicsItem] | None = _field(default=None)
    """Характеристики"""
    created_at: str | None = _field(default=None, name="createdAt")
    """Date and time the item was listed"""
    dimensions: GetCardsTrashResponseCardsItemDimensions | None = _field(default=None)
    """Габариты и вес товара c упаковкой, см и кг"""
    kiz_marked: bool | None = _field(default=None, name="kizMarked")
    """Есть ли подтверждение от продавца, что обязательный код маркировки Честного знака нанесён на
    товар:   - `true` — да   - `false` — нет …
    """
    nm_id: int | None = _field(default=None, name="nmID")
    """Артикул WB"""
    photos: list[GetCardsTrashResponseCardsItemPhotosItem] | None = _field(default=None)
    """Массив фото"""
    sizes: list[GetCardsTrashResponseCardsItemSizesItem] | None = _field(default=None)
    """Массив размеров"""
    subject_id: int | None = _field(default=None, name="subjectID")
    """ID предмета"""
    subject_name: str | None = _field(default=None, name="subjectName")
    """Название предмета"""
    trashed_at: str | None = _field(default=None, name="trashedAt")
    """Дата и время помещения в корзину"""
    vendor_code: str | None = _field(default=None, name="vendorCode")
    """Артикул продавца"""
    video: str | None = _field(default=None)
    """URL видео"""
    wholesale: GetCardsTrashResponseCardsItemWholesale | None = _field(default=None)
    """Оптовая продажа"""


class GetCardsTrashResponseCardsItemCharacteristicsItem(WBModel):
    id: int | None = _field(default=None)
    """ID характеристики"""
    name: str | None = _field(default=None)
    """Название характеристики"""
    value: Any | None = _field(default=None)
    """Значение характеристики. Тип значения зависит от типа характеристики"""


class GetCardsTrashResponseCardsItemDimensions(WBModel):
    """Габариты и вес товара c упаковкой, см и кг"""

    height: int | None = _field(default=None)
    """Высота, см"""
    is_valid: bool | None = _field(default=None, name="isValid")
    """Потенциальная некорректность габаритов товара: …"""
    length: int | None = _field(default=None)
    """Длина, см"""
    weight_brutto: float | None = _field(default=None, name="weightBrutto")
    """Вес, кгКоличество знаков после запятой <=3"""
    width: int | None = _field(default=None)
    """Ширина, см"""


class GetCardsTrashResponseCardsItemPhotosItem(WBModel):
    big: str | None = _field(default=None)
    """URL фото `900x1200`"""
    c246x328: str | None = _field(default=None)
    """URL фото `248x328`"""
    c516x688: str | None = _field(default=None)
    """URL фото `516x688`"""
    square: str | None = _field(default=None)
    """URL фото `600x600`"""
    tm: str | None = _field(default=None)
    """URL фото `75x100`"""


class GetCardsTrashResponseCardsItemSizesItem(WBModel):
    chrt_id: int | None = _field(default=None, name="chrtID")
    """ID размера"""
    skus: list[str] | None = _field(default=None)
    """Массив баркодов"""
    tech_size: str | None = _field(default=None, name="techSize")
    """Размер товара"""
    wb_size: str | None = _field(default=None, name="wbSize")
    """Российский размер товара"""


class GetCardsTrashResponseCardsItemWholesale(WBModel):
    """Оптовая продажа"""

    enabled: bool | None = _field(default=None)
    """Предназначена ли карточка товара для оптовой продажи"""
    quantum: float | None = _field(default=None)
    """Количество единиц товара в упаковке"""


class GetCardsTrashResponseCursor(WBModel):
    """Пагинатор"""

    nm_id: int | None = _field(default=None, name="nmID")
    """Артикул WB, с которого надо запрашивать следующий список карточек товаров"""
    total: int | None = _field(default=None)
    """Количество возвращённых карточек товаров"""
    trashed_at: str | None = _field(default=None, name="trashedAt")
    """Дата и время, с которых надо запрашивать следующий список карточек товаров"""


class GetCardsTrashSettings(WBModel):
    """Настройки"""

    cursor: GetCardsTrashSettingsCursor | None = _field(default=None)
    """Пагинатор"""
    filter: GetCardsTrashSettingsFilter | None = _field(default=None)
    """Параметры фильтрации"""
    sort: GetCardsTrashSettingsSort | None = _field(default=None)
    """Параметр сортировки"""


class GetCardsTrashSettingsCursor(WBModel):
    """Пагинатор"""

    limit: int | None = _field(default=None)
    """Сколько карточек товаров выдать в ответе"""
    nm_id: int | None = _field(default=None, name="nmID")
    """Артикул WB, с которого надо запрашивать следующий список карточек товаров"""
    trashed_at: str | None = _field(default=None, name="trashedAt")
    """Дата и время помещения в корзину"""


class GetCardsTrashSettingsFilter(WBModel):
    """Параметры фильтрации"""

    text_search: str | None = _field(default=None, name="textSearch")
    """Поиск по артикулу продавца, артикулу WB, баркоду"""


class GetCardsTrashSettingsSort(WBModel):
    """Параметр сортировки"""

    ascending: bool | None = _field(default=None)
    """Сортировать по `trashedAt`:   - `false` — по убыванию   - `true` — по возрастанию"""


class GetDbwWarehousesContactsResponse(WBModel):
    """Список контактов склада продавца"""

    contacts: list[GetDbwWarehousesContactsResponseContactsItem] | None = _field(default=None)


class GetDbwWarehousesContactsResponseContactsItem(WBModel):
    comment: str | None = _field(default=None)
    """Комментарий"""
    phone: str | None = _field(default=None)
    """Номер телефона"""


class GetDirectoryColorsResponse(WBModel):
    additional_errors: str | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: Any | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Флаг ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetDirectoryCountriesResponse(WBModel):
    additional_errors: str | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: Any | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Флаг ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetDirectoryKindsResponse(WBModel):
    additional_errors: str | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: list[str] | None = _field(default=None)
    """Массив значений для хар-ки Пол"""
    error: bool | None = _field(default=None)
    """Флаг ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetDirectorySeasonsResponse(WBModel):
    additional_errors: str | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: list[str] | None = _field(default=None)
    """Массив значений для хар-ки Сезон"""
    error: bool | None = _field(default=None)
    """Флаг ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetDirectoryTnvedResponse(WBModel):
    additional_errors: str | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: list[GetDirectoryTnvedResponseDataItem] | None = _field(default=None)
    """Данные"""
    error: bool | None = _field(default=None)
    """Флаг наличия ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Текст ошибки"""


class GetDirectoryTnvedResponseDataItem(WBModel):
    is_kiz: bool | None = _field(default=None, name="isKiz")
    """- `true` — код маркировки Честного знака требуется - `false` — код маркировки Честного знака
    не требуется
    """
    tnved: str | None = _field(default=None)
    """ТНВЭД-код"""


class GetDirectoryVatResponse(WBModel):
    additional_errors: str | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: list[str] | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Флаг наличия ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Текст ошибки"""


class GetObjectAllResponse(WBModel):
    additional_errors: str | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: list[GetObjectAllResponseDataItem] | None = _field(default=None)
    """Предметы"""
    error: bool | None = _field(default=None)
    """Флаг наличия ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Текст ошибки"""


class GetObjectAllResponseDataItem(WBModel):
    parent_id: int | None = _field(default=None, name="parentID")
    """ID родительской категории"""
    parent_name: str | None = _field(default=None, name="parentName")
    """Название родительской категории"""
    subject_id: int | None = _field(default=None, name="subjectID")
    """ID предмета"""
    subject_name: str | None = _field(default=None, name="subjectName")
    """Название предмета"""


class GetObjectCharcsResponse(WBModel):
    additional_errors: str | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: list[GetObjectCharcsResponseDataItem] | None = _field(default=None)
    """Данные"""
    error: bool | None = _field(default=None)
    """Флаг наличия ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Текст ошибки"""


class GetObjectCharcsResponseDataItem(WBModel):
    charc_id: int | None = _field(default=None, name="charcID")
    """ID характеристики"""
    charc_type: int | None = _field(default=None, name="charcType")
    """Тип данных характеристики, который необходимо использовать при создании или редактировании
    карточек товаров:   -  `1` — массив строк …
    """
    exist_named_field: bool | None = _field(default=None, name="existNamedField")
    """Как передать характеристику в запросах на cоздание, создание с
    присоединением и редактирование карточек товара: …
    """
    has_filter: bool | None = _field(default=None, name="hasFilter")
    """Ключевая характеристика. Является ли характеристика значимой для покупателей:   - `true` —
    да   - `false` — нет
    """
    is_variable: bool | None = _field(default=None, name="isVariable")
    """Признак меняющейся характеристики. Значение размечает характеристики, по которым варианты
    отличаются друг от друга: …
    """
    max_count: int | None = _field(default=None, name="maxCount")
    """Максимальное количество значений, которое можно присвоить характеристике при создании или
    редактировании карточек товаров. …
    """
    name: str | None = _field(default=None)
    """Название характеристики"""
    popular: bool | None = _field(default=None)
    """Характеристика популярна у пользователей (true - да, false - нет)"""
    required: bool | None = _field(default=None)
    """- `true` — характеристику необходимо обязательно указать в карточке товара - `false` —
    характеристику необязательно указывать
    """
    subject_id: int | None = _field(default=None, name="subjectID")
    """ID предмета"""
    subject_name: str | None = _field(default=None, name="subjectName")
    """Название предмета"""
    unit_name: str | None = _field(default=None, name="unitName")
    """Единица измерения"""


class GetObjectParentAllResponse(WBModel):
    additional_errors: str | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: Any | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Флаг наличия ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetRecomReq(WBModel):
    """Запрос для получения рекомендаций"""

    brand_names: list[str] | None = _field(default=None, name="brandNames")
    """Бренды"""
    limit: int | None = _field(default=None)
    """Количество товаров в ответе"""
    next: int | None = _field(default=None)
    """Курсор. Последний `nmId` в ответе"""
    search: str | None = _field(default=None)
    """Поиск:   - по артикулу WB `nmId` — полное совпадение   - по артикулу продавца `vendorCode` —
    частичное совпадение
    """
    subject_ids: list[int] | None = _field(default=None, name="subjectIds")
    """ID предметов"""


class GetRecomRes(WBModel):
    """Товары с рекомендациями"""

    data: list[GetRecomResDataItem] | None = _field(default=None)
    """Данные о товарах и их рекомендациях"""
    next: int | None = _field(default=None)
    """Курсор. Последний `nmId` в ответе"""


class GetRecomResDataItem(WBModel):
    brand_name: str | None = _field(default=None, name="brandName")
    """Бренд"""
    imt_id: int | None = _field(default=None, name="imtId")
    """ID для объединённых карточек товаров"""
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""
    pic: str | None = _field(default=None)
    """URL основного изображения в карточке товара"""
    pics_count: int | None = _field(default=None, name="picsCount")
    """Количество изображений в карточке товара"""
    recom_count: int | None = _field(default=None, name="recomCount")
    """Количество рекомендуемых товаров"""
    recom_nms: list[int] | None = _field(default=None, name="recomNms")
    """Список `nmId` рекомендуемых товаров"""
    recom_pics: list[str] | None = _field(default=None, name="recomPics")
    """Список URL основных изображений рекомендуемых товаров"""
    subject_name: str | None = _field(default=None, name="subjectName")
    """Предмет"""
    title: str | None = _field(default=None)
    """Название товара"""
    updated_at: str | None = _field(default=None, name="updatedAt")
    """Дата и время последнего обновления рекомендаций"""
    vendor_code: str | None = _field(default=None, name="vendorCode")
    """Артикул продавца"""


class GetStocksBody(WBModel):
    chrt_ids: list[int] | None = _field(default=None, name="chrtIds")
    """Массив ID размеров товаров"""


class GetStocksResponse(WBModel):
    stocks: list[GetStocksResponseStocksItem] | None = _field(default=None)


class GetStocksResponseStocksItem(WBModel):
    amount: int | None = _field(default=None)
    """Остаток"""
    chrt_id: int | None = _field(default=None, name="chrtId")
    """ID размера товара"""


class GetTagsResponse(WBModel):
    additional_errors: str | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: list[GetTagsResponseDataItem] | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Флаг ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetTagsResponseDataItem(WBModel):
    color: str | None = _field(default=None)
    """Цвет ярлыка"""
    id: int | None = _field(default=None)
    """Числовой ID ярлыка"""
    name: str | None = _field(default=None)
    """Имя ярлыка"""


class ModelsErrorTableListPublicRespV2(WBModel):
    """Данные ответа"""

    cursor: ViewerContractPublicErrorsCursorOutput | None = _field(default=None)
    items: list[ModelsErrorTableListPublicRespV2Item] | None = _field(default=None)
    """Пакеты данных"""


class ModelsErrorTableListPublicRespV2Item(WBModel):
    batch_uuid: str | None = _field(default=None, name="batchUUID")
    """ID пакета"""
    brands: dict[str, Any] | None = _field(default=None)
    """Бренды. Разбивка по `vendorCodes`"""
    errors: dict[str, Any] | None = _field(default=None)
    """Ошибки. Разбивка по `vendorCodes`"""
    subjects: dict[str, Any] | None = _field(default=None)
    """Предметы. Разбивка по `vendorCodes`"""
    updated_at: str | None = _field(default=None, name="updatedAt")
    """Дата и время создания или редактирования пакета"""
    vendor_codes: list[str] | None = _field(default=None, name="vendorCodes")
    """Артикулы продавца"""


class Office(WBModel):
    """Данные о складе WB"""

    address: str | None = _field(default=None)
    """Адрес"""
    cargo_type: int | None = _field(default=None, name="cargoType")
    """Тип товара, который принимает склад:   - `1` — малогабаритный товар (МГТ)   - `3` —
    крупногабаритный товар (КГТ+)
    """
    city: str | None = _field(default=None)
    """Город"""
    delivery_type: int | None = _field(default=None, name="deliveryType")
    """Тип доставки, который принимает склад:   - `1` — доставка на склад WB (FBS)   - `2` —
    доставка силами продавца (DBS)   - `3` — доставка курьером WB (DBW) …
    """
    federal_district: str | None = _field(default=None, name="federalDistrict")
    """Федеральный округ склада WB. Если `null`, склад находится за пределами РФ или федеральный
    округ не указан
    """
    id: int | None = _field(default=None)
    """ID"""
    latitude: float | None = _field(default=None)
    """Широта"""
    longitude: float | None = _field(default=None)
    """Долгота"""
    name: str | None = _field(default=None)
    """Название"""
    selected: bool | None = _field(default=None)
    """Признак того, что склад уже выбран продавцом"""


class RequestMoveNmsImtConn(WBModel):
    nm_ids: list[int] | None = _field(default=None, name="nmIDs")
    """`nmID`, которые необходимо объединить"""
    target_imt: int | None = _field(default=None, name="targetIMT")
    """Существующий `imtID`, под которым необходимо объединить карточки товаров"""


class RequestPublicViewerPublicErrorsTableListV2(WBModel):
    cursor: SwaggerPublicErrorsCursorInput | None = _field(default=None)
    order: SwaggerPublicErrorsOrderV2 | None = _field(default=None)


class ResponseContentError(WBModel):
    additional_errors: str | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: dict[str, Any] | None = _field(default=None)
    """Данные ошибки"""
    error: bool | None = _field(default=None)
    """Флаг ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Текст ошибки"""


class ResponseItemList(WBModel):
    additional_errors: ResponseItemListAdditionalErrors | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: dict[str, Any] | None = _field(default=None)
    """Данные ответа"""
    error: bool | None = _field(default=None)
    """Флаг ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class ResponseItemListAdditionalErrors(WBModel):
    string: str | None = _field(default=None)


class ResponsePublicViewerPublicErrorsTableListV2(WBModel):
    additional_errors: dict[str, Any] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: ModelsErrorTableListPublicRespV2 | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Флаг ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class SetRecomReq(WBModel):
    """Запрос на добавление или замену рекомендаций"""

    rec_list: list[SetRecomReqRecListItem] | None = _field(default=None, name="recList")
    """Список рекомендаций для товаров"""
    replace: bool | None = _field(default=None)
    """Действие в запросе:   - `false` — добавить новые рекомендации к существующим   - `true` —
    заменить существующие рекомендации новыми
    """


class SetRecomReqRecListItem(WBModel):
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""
    recommendations: list[SetRecomReqRecListItemRecommendationsItem] | None = _field(default=None)
    """Рекомендуемые товары.  Укажите `recomNm` товаров, чтобы добавить их в рекомендации к
    указанному `nmId`. …
    """


class SetRecomReqRecListItemRecommendationsItem(WBModel):
    recom_nm: int | None = _field(default=None, name="recomNm")
    """Артикул WB рекомендуемого товара"""
    sort: int | None = _field(default=None)
    """Позиция товара в списке рекомендаций.   Допустимые значения:  - `1`–`20` — фиксированная
    позиция: …
    """


class SetRecomRes(WBModel):
    errors: list[SetRecomResErrorsItem] | None = _field(default=None)
    """Ошибки. При `"isError":true`"""
    is_error: bool | None = _field(default=None, name="isError")
    """Есть ли ошибки:   - `false` — ошибок нет. Запрос полностью успешен   - `true` — ошибки есть
    """


class SetRecomResErrorsItem(WBModel):
    """Ошибки установки рекомендаций"""

    main_nm: str | None = _field(default=None, name="mainNm")
    """Значение параметра `nmId`"""
    message: str | None = _field(default=None)
    """Сообщение об ошибке"""
    recom_nm: str | None = _field(default=None, name="recomNm")
    """Значение параметра `recomNm`"""


class SetRecommendationRecListItem(WBModel):
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""
    recommendations: list[SetRecommendationRecListItemRecommendationsItem] | None = _field(default=None)
    """Рекомендуемые товары.  Укажите `recomNm` товаров, чтобы добавить их в рекомендации к
    указанному `nmId`. …
    """


class SetRecommendationRecListItemRecommendationsItem(WBModel):
    recom_nm: int | None = _field(default=None, name="recomNm")
    """Артикул WB рекомендуемого товара"""
    sort: int | None = _field(default=None)
    """Позиция товара в списке рекомендаций.   Допустимые значения:  - `1`–`20` — фиксированная
    позиция: …
    """


class StoreContactRequestBody(WBModel):
    """Контакты склада продавца"""

    contacts: list[StoreContactRequestBodyContactsItem] | None = _field(default=None)


class StoreContactRequestBodyContactsItem(WBModel):
    comment: str | None = _field(default=None)
    """Комментарий"""
    phone: str | None = _field(default=None)
    """Номер телефона.Поддерживаются коды стран:   - `+7` — Россия, Казахстан   - `+374` — Армения
    - `+375` — Беларусь   - `+996` — Кыргызстан
    """


class SwaggerPublicErrorsCursorInput(WBModel):
    """Пагинатор"""

    batch_uuid: str | None = _field(default=None, name="batchUUID")
    """ID последнего пакета в ответе на предыдущий запрос"""
    limit: float | None = _field(default=None)
    """Количество пакетов в ответе"""
    updated_at: str | None = _field(default=None, name="updatedAt")
    """Дата и время формирования последнего пакета в ответе на предыдущий запрос"""


class SwaggerPublicErrorsOrderV2(WBModel):
    """Порядок выдачи пакетов"""

    ascending: bool | None = _field(default=None)
    """- `false` — сортировка по убыванию - `true` — сортировка по возрастанию"""


class UpdateCardBodyItem(WBModel):
    brand: str | None = _field(default=None)
    """Бренд"""
    characteristics: list[UpdateCardBodyItemCharacteristicsItem] | None = _field(default=None)
    """Характеристики товара.  Можно получить методом Характеристики предмета"""
    description: str | None = _field(default=None)
    """Описание товара. Максимальное количество символов зависит от категории товара Стандарт —
    2000, минимум — 1000, максимум — 5000 …
    """
    dimensions: UpdateCardBodyItemDimensions | None = _field(default=None)
    """Габариты и вес товара **c упаковкой**. Укажите в `сантиметрах` и `килограммах` для любого
    товара. …
    """
    kiz_marked: bool | None = _field(default=None, name="kizMarked")
    """Подтверждение, что на товар нанесён обязательный код маркировки Честного знака: …"""
    nm_id: int | None = _field(default=None, name="nmID")
    """Артикул WB"""
    sizes: list[UpdateCardBodyItemSizesItem] | None = _field(default=None)
    """Массив размеров Для безразмерного товара всё равно нужно передавать данный массив без
    параметров (wbSize и techSize), но с баркодом
    """
    title: str | None = _field(default=None)
    """Наименование товара"""
    vendor_code: str | None = _field(default=None, name="vendorCode")
    """Артикул продавца"""


class UpdateCardBodyItemCharacteristicsItem(WBModel):
    id: int | None = _field(default=None)
    """ID характеристики"""
    value: Any | None = _field(default=None)
    """Значения характеристики.  Тип данных — массив строк или число — зависит от типа
    характеристики, см. описание поля `charcType` в методе Характеристики предмета. …
    """


class UpdateCardBodyItemDimensions(WBModel):
    """Габариты и вес товара **c упаковкой**.<br>"""

    height: int | None = _field(default=None)
    """Высота, см"""
    length: int | None = _field(default=None)
    """Длина, см"""
    weight_brutto: float | None = _field(default=None, name="weightBrutto")
    """Вес, кгКоличество знаков после запятой <=3"""
    width: int | None = _field(default=None)
    """Ширина, см"""


class UpdateCardBodyItemSizesItem(WBModel):
    chrt_id: int | None = _field(default=None, name="chrtID")
    """ID размера для данного артикула WB Обязателен к заполнению для существующих размеров Для
    добавляемых размеров не указывается
    """
    price: int | None = _field(default=None)
    """Цена товара, ₽ Указывается при добавлении размера"""
    skus: list[str] | None = _field(default=None)
    """Баркоды"""
    tech_size: str | None = _field(default=None, name="techSize")
    """Размер товара (например, XL, S, 45)"""
    wb_size: str | None = _field(default=None, name="wbSize")
    """Российский размер товара"""


class UpdateCardsDeleteTrashBody(WBModel):
    nm_ids: list[int] | None = _field(default=None, name="nmIDs")
    """Артикулы WB"""


class UpdateCardsDeleteTrashResponse(WBModel):
    additional_errors: dict[str, Any] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: dict[str, Any] | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Флаг ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class UpdateCardsRecoverBody(WBModel):
    nm_ids: list[int] | None = _field(default=None, name="nmIDs")
    """Артикулы WB"""


class UpdateCardsRecoverResponse(WBModel):
    additional_errors: dict[str, Any] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: dict[str, Any] | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Флаг ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class UpdateDbwWarehousesContactContactsItem(WBModel):
    comment: str | None = _field(default=None)
    """Комментарий"""
    phone: str | None = _field(default=None)
    """Номер телефона.Поддерживаются коды стран:   - `+7` — Россия, Казахстан   - `+374` — Армения
    - `+375` — Беларусь   - `+996` — Кыргызстан
    """


class UpdateStockBody(WBModel):
    stocks: list[UpdateStockBodyStocksItem] | None = _field(default=None)
    """Массив ID размеров товаров и их остатков"""


class UpdateStockBodyStocksItem(WBModel):
    amount: int | None = _field(default=None)
    """Остаток"""
    chrt_id: int | None = _field(default=None, name="chrtId")
    """ID размера товара"""


class UpdateStockStocksItem(WBModel):
    amount: int | None = _field(default=None)
    """Остаток"""
    chrt_id: int | None = _field(default=None, name="chrtId")
    """ID размера товара"""


class UpdateTagBody(WBModel):
    color: str | None = _field(default=None)
    """Цвет ярлыка"""
    name: str | None = _field(default=None)
    """Имя ярлыка"""


class UpdateWarehouseBody(WBModel):
    name: str | None = _field(default=None)
    """Имя склада продавца"""
    office_id: int | None = _field(default=None, name="officeId")
    """ID склада WB.Нельзя привязывать склад WB, который уже используется.Можно менять не чаще
    одного раза в сутки
    """


class UploadMediaFileResponse(WBModel):
    additional_errors: dict[str, Any] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: dict[str, Any] | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Флаг ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class UploadMediaSaveBody(WBModel):
    data: list[str] | None = _field(default=None)
    """Ссылки на изображения в том порядке, в котором они будут в карточке товара, и на видео, на
    любой позиции массива
    """
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""


class UploadMediaSaveResponse(WBModel):
    additional_errors: dict[str, Any] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: dict[str, Any] | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Флаг ошибки"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class ViewerContractPublicErrorsCursorOutput(WBModel):
    """Пагинатор"""

    batch_uuid: str | None = _field(default=None, name="batchUUID")
    """ID последнего пакета в ответе"""
    next: bool | None = _field(default=None)
    """Есть ли ещё черновики:   - `false` — нет   - `true` — да"""
    updated_at: str | None = _field(default=None, name="updatedAt")
    """Дата и время формирования последнего пакета в ответе"""


class Warehouse(WBModel):
    """Данные о складе продавца"""

    cargo_type: int | None = _field(default=None, name="cargoType")
    """Тип товара:   - `1` — малогабаритный товар (МГТ)   - `2` — сверхгабаритный товар (СГТ)   -
    `3` — крупногабаритный товар (КГТ+)
    """
    delivery_type: int | None = _field(default=None, name="deliveryType")
    """Тип доставки, который принимает склад:   - `1` — доставка на склад WB (FBS)   - `2` —
    доставка силами продавца (DBS)   - `3` — доставка курьером WB (DBW) …
    """
    id: int | None = _field(default=None)
    """ID склада продавца"""
    is_deleting: bool | None = _field(default=None, name="isDeleting")
    """Склад удаляется:   - `false` — нет   - `true` — да  После удаления склад пропадёт из списка
    """
    is_processing: bool | None = _field(default=None, name="isProcessing")
    """Данные склада обновляются:   - `false` — нет   - `true` — да, обновление и удаление остатков
    недоступно  Обновление данных может занимать несколько минут
    """
    name: str | None = _field(default=None)
    """Название склада продавца"""
    office_id: int | None = _field(default=None, name="officeId")
    """ID склада WB"""
