from pydantic import Field

from ...types.base import BaseType


class DetailsForTheSalesReportsByReportIdResponse(BaseType):
    """Details for the Sales Reports by Report ID"""

    report_id: int = Field(alias="reportId")
    date_from: str = Field(alias="dateFrom")
    date_to: str = Field(alias="dateTo")
    create_date: str = Field(alias="createDate")
    currency: str = Field()
    report_type: int = Field(alias="reportType")
    rrd_id: int = Field(alias="rrdId")
    gi_id: int = Field(alias="giId")
    dlv_prc: float = Field(alias="dlvPrc")
    fix_tariff_date_from: str = Field(alias="fixTariffDateFrom")
    fix_tariff_date_to: str = Field(alias="fixTariffDateTo")
    subject_name: str = Field(alias="subjectName")
    nm_id: int = Field(alias="nmId")
    brand_name: str = Field(alias="brandName")
    vendor_code: str = Field(alias="vendorCode")
    title: str = Field()
    tech_size: str = Field(alias="techSize")
    sku: str = Field()
    doc_type_name: str = Field(alias="docTypeName")
    quantity: int = Field()
    retail_price: str = Field(alias="retailPrice")
    retail_amount: str = Field(alias="retailAmount")
    sale_percent: int = Field(alias="salePercent")
    commission_percent: float = Field(alias="commissionPercent")
    office_name: str = Field(alias="officeName")
    seller_oper_name: str = Field(alias="sellerOperName")
    order_dt: str = Field(alias="orderDt")
    sale_dt: str = Field(alias="saleDt")
    rr_date: str = Field(alias="rrDate")
    shk_id: int = Field(alias="shkId")
    retail_price_with_disc: str = Field(alias="retailPriceWithDisc")
    delivery_amount: int = Field(alias="deliveryAmount")
    return_amount: int = Field(alias="returnAmount")
    delivery_service: str = Field(alias="deliveryService")
    gi_box_type_name: str = Field(alias="giBoxTypeName")
    product_discount_for_report: float = Field(alias="productDiscountForReport")
    seller_promo: str = Field(alias="sellerPromo")
    spp: float = Field()
    kvw_base: float = Field(alias="kvwBase")
    kvw: float = Field()
    sup_rating_up: float = Field(alias="supRatingUp")
    is_kgvp_v2: float = Field(alias="isKgvpV2")
    ppvz_sales_commission: str = Field(alias="ppvzSalesCommission")
    for_pay: str = Field(alias="forPay")
    ppvz_reward: str = Field(alias="ppvzReward")
    acquiring_fee: str = Field(alias="acquiringFee")
    acquiring_percent: float = Field(alias="acquiringPercent")
    payment_processing: str = Field(alias="paymentProcessing")
    acquiring_bank: str = Field(alias="acquiringBank")
    vw: str = Field()
    vw_nds: str = Field(alias="vwNds")
    ppvz_office_name: str = Field(alias="ppvzOfficeName")
    ppvz_office_id: int = Field(alias="ppvzOfficeId")
    ppvz_supplier_name: str = Field(alias="ppvzSupplierName")
    ppvz_supplier_inn: str = Field(alias="ppvzSupplierInn")
    declaration_number: str = Field(alias="declarationNumber")
    bonus_type_name: str | None = Field(None, alias="bonusTypeName")
    sticker_id: str = Field(alias="stickerId")
    country: str = Field()
    srv_dbs: bool = Field(alias="srvDbs")
    penalty: str = Field()
    additional_payment: str = Field(alias="additionalPayment")
    rebill_logistic_cost: str = Field(alias="rebillLogisticCost")
    rebill_logistic_org: str | None = Field(None, alias="rebillLogisticOrg")
    paid_storage: str = Field(alias="paidStorage")
    deduction: str = Field()
    paid_acceptance: str = Field(alias="paidAcceptance")
    order_id: int = Field(alias="orderId")
    kiz: str | None = Field(None)
    is_b2b: bool = Field(alias="isB2b")
    trbx_id: str = Field(alias="trbxId")
    installment_cofinancing_amount: str = Field(alias="installmentCofinancingAmount")
    wibes_discount_percent: float = Field(alias="wibesDiscountPercent")
    cashback_amount: str = Field(alias="cashbackAmount")
    cashback_discount: str = Field(alias="cashbackDiscount")
    cashback_commission_change: str = Field(alias="cashbackCommissionChange")
    payment_schedule: str = Field(alias="paymentSchedule")
    delivery_method: str = Field(alias="deliveryMethod")
    seller_promo_id: int = Field(alias="sellerPromoId")
    seller_promo_discount: float = Field(alias="sellerPromoDiscount")
    loyalty_id: int = Field(alias="loyaltyId")
    loyalty_discount: float = Field(alias="loyaltyDiscount")
    uuid_promocode: str = Field(alias="uuidPromocode")
    sale_price_promocode_discount_prc: float = Field(alias="salePricePromocodeDiscountPrc")
    article_substitution: str = Field(alias="articleSubstitution")
    sale_price_affiliated_discount_prc: float = Field(alias="salePriceAffiliatedDiscountPrc")
    agency_vat: float | None = Field(None, alias="agencyVat")
    sale_price_wholesale_discount_prc: float = Field(alias="salePriceWholesaleDiscountPrc")
    order_uid: str = Field(alias="orderUid")
    srid: str = Field()
