from typing import Any

from pydantic import Field

from ...types.base import BaseType


class RealizationSalesReportResponse(BaseType):
    """Realization Sales Report"""

    realizationreport_id: int | None = Field(None)
    date_from: str | None = Field(None)
    date_to: str | None = Field(None)
    create_dt: str | None = Field(None)
    currency_name: str | None = Field(None)
    suppliercontract_code: dict[str, Any] | None = Field(None)
    rrd_id: int | None = Field(None)
    gi_id: int | None = Field(None)
    dlv_prc: float | None = Field(None)
    fix_tariff_date_from: str | None = Field(None)
    fix_tariff_date_to: str | None = Field(None)
    subject_name: str | None = Field(None)
    nm_id: int | None = Field(None)
    brand_name: str | None = Field(None)
    sa_name: str | None = Field(None)
    ts_name: str | None = Field(None)
    barcode: str | None = Field(None)
    doc_type_name: str | None = Field(None)
    quantity: int | None = Field(None)
    retail_price: float | None = Field(None)
    retail_amount: float | None = Field(None)
    sale_percent: int | None = Field(None)
    commission_percent: float | None = Field(None)
    office_name: str | None = Field(None)
    supplier_oper_name: str | None = Field(None)
    order_dt: str | None = Field(None)
    sale_dt: str | None = Field(None)
    rr_dt: str | None = Field(None)
    shk_id: int | None = Field(None)
    retail_price_withdisc_rub: float | None = Field(None)
    delivery_amount: int | None = Field(None)
    return_amount: int | None = Field(None)
    delivery_rub: float | None = Field(None)
    gi_box_type_name: str | None = Field(None)
    product_discount_for_report: float | None = Field(None)
    supplier_promo: float | None = Field(None)
    ppvz_spp_prc: float | None = Field(None)
    ppvz_kvw_prc_base: float | None = Field(None)
    ppvz_kvw_prc: float | None = Field(None)
    sup_rating_prc_up: float | None = Field(None)
    is_kgvp_v2: float | None = Field(None)
    ppvz_sales_commission: float | None = Field(None)
    ppvz_for_pay: float | None = Field(None)
    ppvz_reward: float | None = Field(None)
    acquiring_fee: float | None = Field(None)
    acquiring_percent: float | None = Field(None)
    payment_processing: str | None = Field(None)
    acquiring_bank: str | None = Field(None)
    ppvz_vw: float | None = Field(None)
    ppvz_vw_nds: float | None = Field(None)
    ppvz_office_name: str | None = Field(None)
    ppvz_office_id: int | None = Field(None)
    ppvz_supplier_id: int | None = Field(None)
    ppvz_supplier_name: str | None = Field(None)
    ppvz_inn: str | None = Field(None)
    declaration_number: str | None = Field(None)
    bonus_type_name: str | None = Field(None)
    sticker_id: str | None = Field(None)
    site_country: str | None = Field(None)
    srv_dbs: bool | None = Field(None)
    penalty: float | None = Field(None)
    additional_payment: float | None = Field(None)
    rebill_logistic_cost: float | None = Field(None)
    rebill_logistic_org: str | None = Field(None)
    storage_fee: float | None = Field(None)
    deduction: float | None = Field(None)
    acceptance: float | None = Field(None)
    assembly_id: int | None = Field(None)
    kiz: str | None = Field(None)
    srid: str | None = Field(None)
    report_type: int | None = Field(None)
    is_legal_entity: bool | None = Field(None)
    trbx_id: str | None = Field(None)
    installment_cofinancing_amount: float | None = Field(None)
    wibes_wb_discount_percent: float | None = Field(None)
    cashback_amount: float | None = Field(None)
    cashback_discount: float | None = Field(None)
    cashback_commission_change: float | None = Field(None)
    order_uid: str | None = Field(None)
    payment_schedule: float | None = Field(None)
    delivery_method: str | None = Field(None)
    seller_promo_id: int | None = Field(None)
    seller_promo_discount: float | None = Field(None)
    loyalty_id: int | None = Field(None)
    loyalty_discount: float | None = Field(None)
    uuid_promocode: str | None = Field(None)
    sale_price_promocode_discount_prc: float | None = Field(None)
