# @generated
# This file was auto-generated by scripts/codegen.py from specs/. Do not edit by hand.

from __future__ import annotations

from typing import Any

from msgspec import field as _field

from ..client.model import WBModel


class AdvertBidsKopecks(WBModel):
    """Ставка в разменных единицах — 0,01 от базовой валюты [аккаунта продавца](https://cmp.wil"""

    recommendations: int | None = _field(default=None)
    """Ставка в рекомендациях"""
    search: int | None = _field(default=None)
    """Ставка в поиске"""


class AdvertNMsSettings(WBModel):
    bids_kopecks: AdvertBidsKopecks | None = _field(default=None)
    nm_id: int | None = _field(default=None)
    """Артикул WB"""
    subject: AdvertSubcategory | None = _field(default=None)


class AdvertSettings(WBModel):
    """Настройки кампании"""

    name: str | None = _field(default=None)
    """Название кампании"""
    payment_type: str | None = _field(default=None)
    """Тип оплаты: - `cpm` — за показы - `cpc` — за клик"""
    placements: AdvertSettingsPlacements | None = _field(default=None)
    """Места размещения"""


class AdvertSettingsPlacements(WBModel):
    """Места размещения"""

    recommendations: bool | None = _field(default=None)
    """Размещение в рекомендациях:   - `false` — отключено   - `true` — включено"""
    search: bool | None = _field(default=None)
    """Размещение в поиске:   - `false` — отключено   - `true` — включено"""


class AdvertSubcategory(WBModel):
    """Предмет"""

    id: int | None = _field(default=None)
    """ID предмета"""
    name: str | None = _field(default=None)
    """Название предмета"""


class CreateAdvertBidsMinBody(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    nm_ids: list[int] | None = _field(default=None)
    """Список артикулов WB"""
    payment_type: str | None = _field(default=None)
    """Тип оплаты:       - `cpm` — за показы       - `cpc` — за клик"""
    placement_types: list[str] | None = _field(default=None)
    """Места размещения:   - `search` — поиск   - `recommendation` — рекомендации   - `combined` —
    поиск и рекомендации
    """


class CreateAdvertBidsMinResponse(WBModel):
    bids: list[CreateAdvertBidsMinResponseBidsItem] | None = _field(default=None)
    """Список карточек товаров со ставками"""


class CreateAdvertBidsMinResponseBidsItem(WBModel):
    bids: list[CreateAdvertBidsMinResponseBidsItemBidsItem] | None = _field(default=None)
    """Список ставок по местам размещения"""
    nm_id: int | None = _field(default=None)
    """Артикул WB"""


class CreateAdvertBidsMinResponseBidsItemBidsItem(WBModel):
    currency: str | None = _field(default=None)
    """Валюта аккаунта продавца"""
    type: str | None = _field(default=None)
    value: int | None = _field(default=None)
    """Минимальная ставка в разменных единицах — 0,01 от базовой валюты аккаунта продавца"""


class CreateBudgetDepositBody(WBModel):
    cashback_percent: int | None = _field(default=None)
    """Процент от суммы пополнения, который можно пополнить промо-бонусами. Нужно указать значение
    поля percent из ответа метода получения баланса …
    """
    cashback_sum: int | None = _field(default=None)
    """Сумма пополнения бюджета промо-бонусами. …"""
    return_: bool | None = _field(default=None, name="return")
    """Флаг возврата ответа (`true` — в ответе вернется обновлённый размер бюджета кампании,
    `false` или не указать параметр вообще — не вернётся.)
    """
    sum: int | None = _field(default=None)
    """Общая сумма пополнения бюджета в базовых единицах валюты аккаунта продавца"""
    type: int | None = _field(default=None)
    """Тип источника пополнения: - `0` — Счёт - `1` — Баланс - `3` — Бонусы"""


class CreateRenameBody(WBModel):
    advert_id: int | None = _field(default=None, name="advertId")
    """ID кампании, в которой меняется название"""
    name: str | None = _field(default=None)
    """Новое название (максимум 100 символов)"""


class CreateSeacatSaveAdBody(WBModel):
    bid_type: str | None = _field(default=None)
    """Тип ставки:   - `manual` — ручная   - `unified` — единая"""
    name: str | None = _field(default=None)
    """Название кампании"""
    nms: list[int] | None = _field(default=None)
    """Карточки товаров для кампании. Доступные карточки товаров можно получить с помощью метода
    Карточки товаров для кампаний. Максимум 50 товаров (`nm`)
    """
    payment_type: str | None = _field(default=None)
    """Тип оплаты: - `cpm` — за показы - `cpc` — за клик. При создании с этим типом оплаты в
    кампании автоматически устанавливается минимальная ставка
    """
    placement_types: list[str] | None = _field(default=None)
    """Места размещения:   - `search` — в поиске   - `recommendations` — в рекомендациях  Укажите
    только для кампании с ручной ставкой
    """


class CreateSupplierNmsResponseItem(WBModel):
    nm: int | None = _field(default=None)
    """Артикул WB"""
    subject_id: int | None = _field(default=None, name="subjectId")
    """ID предмета"""
    title: str | None = _field(default=None)
    """Название товара"""


class FullStatsItem(WBModel):
    """Статистика по одной кампании за период, указанный в запросе. По всем артикулам WB и плат"""

    advert_id: int | None = _field(default=None, name="advertId")
    """ID кампании"""
    atbs: int | None = _field(default=None)
    """Количество добавлений товаров в корзину"""
    booster_stats: list[FullStatsItemBoosterStatsItem] | None = _field(default=None, name="boosterStats")
    canceled: int | None = _field(default=None)
    """Отмены, шт."""
    clicks: int | None = _field(default=None)
    """Количество кликов"""
    cpc: float | None = _field(default=None)
    """Средняя стоимость клика в базовых единицах валюты аккаунта продавца"""
    cr: float | None = _field(default=None)
    """CR (conversion rate) — отношение количества заказов к общему количеству кликов"""
    ctr: float | None = _field(default=None)
    """CTR (click-through rate) — отношение числа кликов к количеству показов в процентах"""
    currency: str | None = _field(default=None)
    """Валюта аккаунта продавца"""
    days: list[FullStatsItemDaysItem] | None = _field(default=None)
    orders: int | None = _field(default=None)
    """Количество заказов"""
    shks: int | None = _field(default=None)
    """Количество заказанных товаров, шт."""
    sum: float | None = _field(default=None)
    """Затраты в базовых единицах валюты аккаунта продавца"""
    sum_price: float | None = _field(default=None)
    """Сумма заказов в базовых единицах валюты аккаунта продавца"""
    views: int | None = _field(default=None)
    """Количество просмотров"""


class FullStatsItemBoosterStatsItem(WBModel):
    avg_position: int | None = _field(default=None)
    """Средняя позиция товара"""
    date: str | None = _field(default=None)
    """Дата, за которую предоставлены данные"""
    nm: int | None = _field(default=None)
    """Артикул WB"""


class FullStatsItemDaysItem(WBModel):
    apps: list[FullStatsItemDaysItemAppsItem] | None = _field(default=None)
    """Блок информации о платформе"""
    atbs: int | None = _field(default=None)
    """Количество добавлений товаров в корзину"""
    canceled: int | None = _field(default=None)
    """Отмены, шт."""
    clicks: int | None = _field(default=None)
    """Количество кликов"""
    cpc: float | None = _field(default=None)
    """Средняя стоимость клика в базовых единицах валюты аккаунта продавца"""
    cr: float | None = _field(default=None)
    """CR (conversion rate) — отношение количества заказов к общему количеству посещений кампании
    """
    ctr: float | None = _field(default=None)
    """CTR (click-through rate) — отношение числа кликов к количеству показов в процентах"""
    date: str | None = _field(default=None)
    """Дата, за которую представлены данные"""
    orders: int | None = _field(default=None)
    """Количество заказов"""
    shks: int | None = _field(default=None)
    """Количество заказанных товаров, шт."""
    sum: float | None = _field(default=None)
    """Затраты в базовых единицах валюты аккаунта продавца"""
    sum_price: float | None = _field(default=None)
    """Заказов на сумму в базовых единицах валюты аккаунта продавца"""
    views: int | None = _field(default=None)
    """Количество просмотров"""


class FullStatsItemDaysItemAppsItem(WBModel):
    app_type: int | None = _field(default=None, name="appType")
    """Тип платформы:   - `1` — сайт   - `32` — Android   - `64` — IOS"""
    atbs: int | None = _field(default=None)
    """Количество добавлений товаров в корзину"""
    canceled: int | None = _field(default=None)
    """Отмены, шт."""
    clicks: int | None = _field(default=None)
    """Количество кликов"""
    cpc: float | None = _field(default=None)
    """Средняя стоимость клика в базовых единицах валюты аккаунта продавца"""
    cr: float | None = _field(default=None)
    """CR (conversion rate) — отношение количества заказов к общему количеству кликов"""
    ctr: float | None = _field(default=None)
    """CTR (click-through rate) — отношение числа кликов к количеству показов в процентах"""
    nms: list[FullStatsItemDaysItemAppsItemNmsItem] | None = _field(default=None)
    """Блок статистики по артикулам WB"""
    orders: int | None = _field(default=None)
    """Количество заказов"""
    shks: int | None = _field(default=None)
    """Количество заказанных товаров, шт."""
    sum: float | None = _field(default=None)
    """Затраты в базовых единицах валюты аккаунта продавца"""
    sum_price: float | None = _field(default=None)
    """Заказов на сумму в базовых единицах валюты аккаунта продавца"""
    views: int | None = _field(default=None)
    """Количество просмотров"""


class FullStatsItemDaysItemAppsItemNmsItem(WBModel):
    atbs: int | None = _field(default=None)
    """Количество добавлений товаров в корзину"""
    canceled: int | None = _field(default=None)
    """Отмены, шт."""
    clicks: int | None = _field(default=None)
    """Количество кликов"""
    cpc: float | None = _field(default=None)
    """Средняя стоимость клика в базовых единицах валюты аккаунта продавца"""
    cr: float | None = _field(default=None)
    """CR (conversion rate) — отношение количества заказов к общему количеству кликов"""
    ctr: float | None = _field(default=None)
    """CTR (click-through rate) — отношение числа кликов к количеству показов в процентах"""
    name: str | None = _field(default=None)
    """Название товара"""
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""
    orders: int | None = _field(default=None)
    """Количество заказов"""
    shks: int | None = _field(default=None)
    """Количество заказанных товаров, шт."""
    sum: float | None = _field(default=None)
    """Затраты в базовых единицах валюты аккаунта продавца"""
    sum_price: float | None = _field(default=None)
    """Заказов на сумму в базовых единицах валюты аккаунта продавца"""
    views: int | None = _field(default=None)
    """Количество просмотров"""


class GetAdvertResponse(WBModel):
    advert_id: int | None = _field(default=None, name="advertId")
    """ID медиакампании"""
    brand: str | None = _field(default=None)
    """Название бренда"""
    create_time: str | None = _field(default=None, name="createTime")
    """Время создания медиакампании"""
    extended: GetAdvertResponseExtended | None = _field(default=None)
    items: list[GetAdvertResponseItemsItem] | None = _field(default=None)
    """Информация о баннере.  Наличие в ответе тех или иных полей зависит от конфигурации
    медиакампании.
    """
    name: str | None = _field(default=None)
    """Название медиакампании"""
    status: int | None = _field(default=None)
    """Статус медиакампании:   - `1` — черновик   - `2` — модерация   - `3` — отклонена (с
    возможностью вернуть на модерацию)   - `4` — готова к запуску …
    """
    type: int | None = _field(default=None)
    """Тип медиакампании: - `1` — размещение по дням - `2` — размещение по просмотрам"""


class GetAdvertResponseExtended(WBModel):
    budget: int | None = _field(default=None)
    """Остаток бюджета для типа `2`"""
    contract_id: int | None = _field(default=None)
    """ID контракта, для продавцов на контракте"""
    expenses: int | None = _field(default=None)
    """Затраты"""
    from_: str | None = _field(default=None, name="from")
    """Дата и время начала показа медиакампании"""
    operation: int | None = _field(default=None)
    """Источник списания:   - `1` — баланс   - `2` — счёт"""
    price: int | None = _field(default=None)
    """Стоимость размещения по дням для типа `1`"""
    reason: str | None = _field(default=None)
    """Комментарий модератора"""
    to: str | None = _field(default=None)
    """Дата и время окончания показа медиакампании"""
    updated_at: str | None = _field(default=None)
    """Дата и время изменения кампании"""


class GetAdvertResponseItemsItem(WBModel):
    erid: str | None = _field(default=None, name="Erid")
    """Уникальный ID медиакампании для работы с ОРД"""
    action_name: str | None = _field(default=None)
    """Название акции"""
    additional_settings: int | None = _field(default=None, name="additionalSettings")
    """Дополнительные настройки.  Формат почтовой рассылки: - `1` — общий - `2` — частичный - `3` —
    уникальный  Социальная сеть: - `1` — VK - `2` — OK (Одноклассники)
    """
    advert_type: int | None = _field(default=None)
    """Тип продвижения: - `1` — баннер - `2` — всплывающее меню - `3` — почтовая рассылка - `4` —
    социальные сети - `5` — push-уведомления в мобильном приложении
    """
    bottom_text1: str | None = _field(default=None, name="bottomText1")
    """Текст под плашкой баннера"""
    bottom_text2: str | None = _field(default=None, name="bottomText2")
    """2-я строка с текстом под плашкой баннера"""
    budget: int | None = _field(default=None)
    """Бюджет"""
    category_name: str | None = _field(default=None)
    """Название категории размещения"""
    cpm: int | None = _field(default=None)
    """Ставка"""
    created_at: str | None = _field(default=None)
    """Дата создания баннера"""
    daily_limit: int | None = _field(default=None)
    """Дневной лимит (для баннеров по показам)"""
    date_from: str | None = _field(default=None)
    """Дата начала работы баннера"""
    date_to: str | None = _field(default=None)
    """Дата завершения работы баннера"""
    id: int | None = _field(default=None)
    """ID баннера"""
    message: str | None = _field(default=None)
    """Текст push-уведомления или рассылки"""
    name: str | None = _field(default=None)
    """Бренд"""
    nms: list[int] | None = _field(default=None)
    """Подборка артикулов WB"""
    place: int | None = _field(default=None)
    """Позиция на странице размещения"""
    receivers_count: int | None = _field(default=None, name="receiversCount")
    """Кол-во получателей push-уведомлений"""
    show_hours: list[GetAdvertResponseItemsItemShowHoursItem] | None = _field(default=None)
    """Часы показа"""
    status: int | None = _field(default=None)
    """Статус (такой же как у медиакампании)"""
    subject_id: int | None = _field(default=None)
    """ID родительской категории товара"""
    subject_name: str | None = _field(default=None)
    """Название родительской категории товара"""
    updated_at: str | None = _field(default=None)
    """Дата и время обновления баннера"""
    url: str | None = _field(default=None)
    """URL страницы, на которую попадает пользователь при клике по баннеру"""


class GetAdvertResponseItemsItemShowHoursItem(WBModel):
    from_: int | None = _field(default=None, name="From")
    """Начало показа"""
    to: int | None = _field(default=None, name="To")
    """Конец показа"""


class GetAdvertsAdvertsItem(WBModel):
    bid_type: str | None = _field(default=None)
    """Тип ставки:   - `unified` — единая ставка   - `manual` — ручная ставка"""
    currency: str | None = _field(default=None)
    """Валюта аккаунта продавца"""
    id: int | None = _field(default=None)
    """ID кампании"""
    nm_settings: list[AdvertNMsSettings] | None = _field(default=None)
    """Настройки товаров"""
    restrictions: GetAdvertsAdvertsItemRestrictions | None = _field(default=None)
    """Ограничения кампании"""
    settings: AdvertSettings | None = _field(default=None)
    status: int | None = _field(default=None)
    """Статус кампании: - `-1` — удалена, процесс удаления будет завершён в течение 10 минут - `4`
    — готова к запуску - `7` — завершена - `8` — отменена …
    """
    timestamps: Timestamps | None = _field(default=None)


class GetAdvertsAdvertsItemRestrictions(WBModel):
    """Ограничения кампании"""

    can_change_nms: bool | None = _field(default=None)
    """Можно ли изменять список товаров кампании:   - `true` — да   - `false` — нет"""


class GetAdvertsModel(WBModel):
    adverts: list[GetAdvertsAdvertsItem] | None = _field(default=None)
    """Кампании"""


class GetAdvertsResponseItem(WBModel):
    advert_id: int | None = _field(default=None, name="advertId")
    """ID медиакампании"""
    brand: str | None = _field(default=None)
    """Название бренда"""
    create_time: str | None = _field(default=None, name="createTime")
    """Время создания медиакампании"""
    end_time: str | None = _field(default=None, name="endTime")
    """Время завершения медиакампании"""
    name: str | None = _field(default=None)
    """Название медиакампании"""
    status: int | None = _field(default=None)
    """Статус медиакампании:   - `1` — черновик   - `2` — модерация   - `3` — отклонена (с
    возможностью вернуть на модерацию)   - `4` — готова к запуску …
    """
    type: int | None = _field(default=None)
    """Тип медиакампании: - `1` — размещение по дням - `2` — размещение по просмотрам"""


class GetBalanceResponse(WBModel):
    balance: int | None = _field(default=None)
    """Счёт в базовых единицах валюты аккаунта продавца"""
    bonus: int | None = _field(default=None)
    """Бонусы в базовых единицах валюты аккаунта продавца"""
    cashbacks: list[GetBalanceResponseCashbacksItem] | None = _field(default=None)
    """Промо-бонусы"""
    currency: str | None = _field(default=None)
    """Валюта аккаунта продавца"""
    net: int | None = _field(default=None)
    """Баланс в базовых единицах валюты аккаунта продавца"""


class GetBalanceResponseCashbacksItem(WBModel):
    expiration_date: str | None = _field(default=None)
    """Дата окончания действия промо-бонусов"""
    percent: int | None = _field(default=None)
    """Процент от суммы пополнения бюджета кампании, который можно оплатить промо-бонусами за один
    раз
    """
    sum: int | None = _field(default=None)
    """Промо-бонусы в базовых единицах валюты аккаунта продавца"""


class GetBudgetResponse(WBModel):
    cash: int | None = _field(default=None)
    """Поле не используется. Значение всегда 0."""
    currency: str | None = _field(default=None)
    """Валюта аккаунта продавца"""
    netting: int | None = _field(default=None)
    """Поле не используется. Значение всегда 0."""
    total: int | None = _field(default=None)
    """Бюджет кампании в базовых единицах валюты аккаунта продавца"""


class GetCountResponse(WBModel):
    adverts: GetCountResponseAdverts | None = _field(default=None)
    all: int | None = _field(default=None)
    """Общее количество медиакампаний всех статусов и типов"""


class GetCountResponseAdverts(WBModel):
    count: int | None = _field(default=None)
    """Количество медиакампаний"""
    status: int | None = _field(default=None)
    """Статус медиакампании:   - `1` — черновик   - `2` — модерация   - `3` — отклонена (с
    возможностью вернуть на модерацию)   - `4` — готова к запуску …
    """
    type: int | None = _field(default=None)
    """Тип медиакампании: - `1` — размещение по дням - `2` — размещение по просмотрам"""


class GetNormqueryStatsItemsItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    nm_id: int | None = _field(default=None)
    """Артикул WB"""


class GetPaymentsResponseItem(WBModel):
    card_status: str | None = _field(default=None, name="cardStatus")
    """Статус операции при оплате картой: - `success` — успех - `fail` — неуспех - `pending` — в
    ожидании ответа - `unknown` — неизвестно
    """
    currency: str | None = _field(default=None)
    """Валюта аккаунта продавца"""
    date: str | None = _field(default=None)
    """Дата платежа"""
    id: int | None = _field(default=None)
    """ID платежа"""
    status_id: int | None = _field(default=None, name="statusId")
    """Статус: - `0` — ошибка - `1` — обработано"""
    sum: int | None = _field(default=None)
    """Сумма платежа"""
    type: int | None = _field(default=None)
    """Тип источника списания: - `0` — Счёт - `1` — Баланс - `3` — Картой"""


class GetPromotionCountResponse(WBModel):
    adverts: list[GetPromotionCountResponseAdvertsItem] | None = _field(default=None)
    """Данные по кампаниям"""
    all: int | None = _field(default=None)
    """Общее количество кампаний всех статусов и типов"""


class GetPromotionCountResponseAdvertsItem(WBModel):
    advert_list: list[GetPromotionCountResponseAdvertsItemAdvertListItem] | None = _field(default=None)
    """Список кампаний"""
    count: int | None = _field(default=None)
    """Количество кампаний"""
    status: int | None = _field(default=None)
    """Статус кампании"""
    type: int | None = _field(default=None)
    """Тип кампании:   - `8` — кампания с единой ставкой (**устаревший тип**) …"""


class GetPromotionCountResponseAdvertsItemAdvertListItem(WBModel):
    advert_id: int | None = _field(default=None, name="advertId")
    """ID кампании"""
    change_time: str | None = _field(default=None, name="changeTime")
    """Дата и время последнего изменения кампании"""


class GetSupplierSubjectsResponseItem(WBModel):
    count: int | None = _field(default=None)
    """Количество Артикулов WB (`nmId`) с таким предметом."""
    id: int | None = _field(default=None)
    """ID предмета"""
    name: str | None = _field(default=None)
    """Предмет"""


class GetUpdResponseItem(WBModel):
    advert_id: int | None = _field(default=None, name="advertId")
    """ID кампании"""
    advert_status: int | None = _field(default=None, name="advertStatus")
    """Статус кампании: - `-1` — удалена, процесс удаления будет завершён в течение 10 минут - `4`
    — готова к запуску - `7` — завершена - `8` — отменена …
    """
    advert_type: int | None = _field(default=None, name="advertType")
    """Тип кампании"""
    camp_name: str | None = _field(default=None, name="campName")
    """Название кампании"""
    payment_type: str | None = _field(default=None, name="paymentType")
    """Источник списания:  - `Баланс`  - `Бонусы`  - `Счёт`  - `Кэшбэк`"""
    upd_num: int | None = _field(default=None, name="updNum")
    """Номер выставленного документа"""
    upd_sum: int | None = _field(default=None, name="updSum")
    """Выставленная сумма в базовых единицах валюты аккаунта продавца"""
    upd_time: str | None = _field(default=None, name="updTime")
    """Время списания"""


class NormQueryBidFailResponseItem(WBModel):
    advert_id: int | None = _field(default=None, name="advertId")
    """ID кампании"""
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""
    norm_query: str | None = _field(default=None, name="normQuery")
    """Поисковый кластер — это группа похожих поисковых запросов, по которым покупатели находят
    товары
    """
    reason: str | None = _field(default=None)
    """Описание причины ошибки"""


class RequestWithDate(WBModel):
    dates: list[str] | None = _field(default=None)
    """Даты, за которые нужно получить информацию"""
    id: int | None = _field(default=None)
    """ID кампании"""


class ResponseWithReturn(WBModel):
    currency: str | None = _field(default=None)
    """Валюта аккаунта продавца"""
    total: int | None = _field(default=None)
    """Размер обновлённого бюджета"""


class StatInterval(WBModel):
    interval: StatIntervalInterval | None = _field(default=None)
    """Период"""
    stats: list[StatsBlok1] | None = _field(default=None)
    """Блок статистики"""


class StatIntervalInterval(WBModel):
    """Период"""

    begin: str | None = _field(default=None)
    """Начало периода"""
    end: str | None = _field(default=None)
    """Конец периода"""


class StatsBlok1(WBModel):
    advert_type: int | None = _field(default=None)
    """Тип медиакампании:   - `1` — размещение по дням   - `2` — размещение по просмотрам"""
    atbs: int | None = _field(default=None)
    """Количество добавлений товаров в корзину"""
    category_name: str | None = _field(default=None)
    """Название категории"""
    clicks: int | None = _field(default=None)
    """Количество кликов"""
    cpc: float | None = _field(default=None)
    """(cost per click) — цена клика по продвигаемому товару"""
    cr: float | None = _field(default=None)
    """CR(conversion rate) — это отношение количества заказов к общему количеству посещений
    медиакампании
    """
    cr1: float | None = _field(default=None)
    """Отношение количества добавлений в корзину к количеству кликов"""
    cr2: int | None = _field(default=None)
    """Отношение количества заказов к количеству добавлений в корзину"""
    ctr: float | None = _field(default=None)
    """CTR (click-through rate) — показатель кликабельности, отношение числа кликов к количеству
    показов в рамках медиакампании
    """
    daily_stats: list[StatsBlok1DailyStatsItem] | None = _field(default=None)
    date_from: str | None = _field(default=None)
    """Время начала размещения"""
    date_to: str | None = _field(default=None)
    """Время завершения размещения"""
    expenses: float | None = _field(default=None)
    """Стоимость размещения баннера"""
    item_id: int | None = _field(default=None)
    """ID баннера"""
    item_name: str | None = _field(default=None)
    """Бренд"""
    orders: int | None = _field(default=None)
    """Количество заказов"""
    place: int | None = _field(default=None)
    """Место на странице"""
    price: float | None = _field(default=None)
    """Стоимость размещения"""
    status: int | None = _field(default=None)
    """Статус медиакампании"""
    subject_name: str | None = _field(default=None)
    """Родительская категория предмета"""
    views: int | None = _field(default=None)
    """Количество просмотров"""


class StatsBlok1DailyStatsItem(WBModel):
    app_type_stats: list[StatsBlok1DailyStatsItemAppTypeStatsItem] | None = _field(default=None)
    """Статистика по платформам"""
    date: str | None = _field(default=None)
    """Дата"""


class StatsBlok1DailyStatsItemAppTypeStatsItem(WBModel):
    app_type: int | None = _field(default=None)
    """Тип платформы: - `1` — сайт - `32` — Android - `64` — IOS"""
    stats: list[StatsBlok1DailyStatsItemAppTypeStatsItemStatsItem] | None = _field(default=None)


class StatsBlok1DailyStatsItemAppTypeStatsItemStatsItem(WBModel):
    atbs: int | None = _field(default=None)
    """Количество добавлений товаров в корзину"""
    clicks: int | None = _field(default=None)
    """Количество кликов"""
    ctr: float | None = _field(default=None)
    """CTR (click-through rate) — показатель кликабельности, отношение числа кликов к количеству
    показов в рамках медиакампании
    """
    views: int | None = _field(default=None)
    """Количество просмотров"""


class Timestamps(WBModel):
    """Временные отметки"""

    created: str | None = _field(default=None)
    """Время создания кампании"""
    deleted: str | None = _field(default=None)
    """Время удаления кампании. Если кампания не удалена, время указывается в будущем"""
    started: str | None = _field(default=None)
    """Время последнего запуска кампании"""
    updated: str | None = _field(default=None)
    """Время последнего изменения кампании"""


class UpdateAdvertBidBidsItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    nm_bids: list[UpdateAdvertBidBidsItemNmBidsItem] | None = _field(default=None)
    """Ставки"""


class UpdateAdvertBidBidsItemNmBidsItem(WBModel):
    bid_kopecks: int | None = _field(default=None)
    """Ставка в разменных единицах — 0,01 от базовой валюты аккаунта продавца"""
    nm_id: int | None = _field(default=None)
    """Артикул WB"""
    placement: str | None = _field(default=None)
    """Место размещения:   - `search` — в поиске (для кампаний с ручной ставкой)   -
    `recommendations`— в рекомендациях (для кампаний с ручной ставкой) …
    """


class UpdateAdvertBidBody(WBModel):
    bids: list[UpdateAdvertBidBodyBidsItem] | None = _field(default=None)
    """Ставки в кампаниях"""


class UpdateAdvertBidBodyBidsItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    nm_bids: list[UpdateAdvertBidBodyBidsItemNmBidsItem] | None = _field(default=None)
    """Ставки"""


class UpdateAdvertBidBodyBidsItemNmBidsItem(WBModel):
    bid_kopecks: int | None = _field(default=None)
    """Ставка в разменных единицах — 0,01 от базовой валюты аккаунта продавца"""
    nm_id: int | None = _field(default=None)
    """Артикул WB"""
    placement: str | None = _field(default=None)
    """Место размещения:   - `search` — в поиске (для кампаний с ручной ставкой)   -
    `recommendations`— в рекомендациях (для кампаний с ручной ставкой) …
    """


class UpdateAdvertBidResponse(WBModel):
    bids: list[UpdateAdvertBidResponseBidsItem] | None = _field(default=None)
    """Результат отработки запроса"""
    currency: str | None = _field(default=None)
    """Валюта аккаунта продавца"""


class UpdateAdvertBidResponseBidsItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    nm_bids: list[UpdateAdvertBidResponseBidsItemNmBidsItem] | None = _field(default=None)
    """Ставки"""


class UpdateAdvertBidResponseBidsItemNmBidsItem(WBModel):
    bid_kopecks: int | None = _field(default=None)
    """Ставка в разменных единицах — 0,01 от базовой валюты аккаунта продавца"""
    nm_id: int | None = _field(default=None)
    """Артикул WB"""
    placement: str | None = _field(default=None)
    """Место размещения:   - `search` — в поиске   - `recommendations`— в рекомендациях"""


class UpdateAuctionNmsBody(WBModel):
    nms: list[UpdateAuctionNmsBodyNmsItem] | None = _field(default=None)
    """Карточки товаров в кампаниях"""


class UpdateAuctionNmsBodyNmsItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    nms: UpdateAuctionNmsBodyNmsItemNms | None = _field(default=None)
    """Карточки товаров. Максимум 50 товаров для одной кампании"""


class UpdateAuctionNmsBodyNmsItemNms(WBModel):
    """Карточки товаров. Максимум 50 товаров для одной кампании"""

    add: Any | None = _field(default=None)
    """Карточки товаров, которые необходимо добавить"""
    delete: list[int] | None = _field(default=None)
    """Карточки товаров, которые необходимо удалить"""


class UpdateAuctionNmsNmsItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    nms: UpdateAuctionNmsNmsItemNms | None = _field(default=None)
    """Карточки товаров. Максимум 50 товаров для одной кампании"""


class UpdateAuctionNmsNmsItemNms(WBModel):
    """Карточки товаров. Максимум 50 товаров для одной кампании"""

    add: Any | None = _field(default=None)
    """Карточки товаров, которые необходимо добавить"""
    delete: list[int] | None = _field(default=None)
    """Карточки товаров, которые необходимо удалить"""


class UpdateAuctionNmsResponse(WBModel):
    nms: list[UpdateAuctionNmsResponseNmsItem] | None = _field(default=None)
    """Результат отработки запроса"""


class UpdateAuctionNmsResponseNmsItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    nms: UpdateAuctionNmsResponseNmsItemNms | None = _field(default=None)
    """Карточки товаров"""


class UpdateAuctionNmsResponseNmsItemNms(WBModel):
    """Карточки товаров"""

    added: list[int] | None = _field(default=None)
    """Добавленные карточки товаров"""
    deleted: list[int] | None = _field(default=None)
    """Удалённые карточки товаров"""


class UpdateAuctionPlacementBody(WBModel):
    placements: list[UpdateAuctionPlacementBodyPlacementsItem] | None = _field(default=None)
    """Места размещения в кампаниях"""


class UpdateAuctionPlacementBodyPlacementsItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    placements: UpdateAuctionPlacementBodyPlacementsItemPlacements | None = _field(default=None)
    """Места размещения"""


class UpdateAuctionPlacementBodyPlacementsItemPlacements(WBModel):
    """Места размещения"""

    recommendations: bool | None = _field(default=None)
    """Размещение в рекомендациях:   - `false` — отключено   - `true` — включено"""
    search: bool | None = _field(default=None)
    """Размещение в поиске:   - `false` — отключено   - `true` — включено"""


class UpdateAuctionPlacementPlacementsItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    placements: UpdateAuctionPlacementPlacementsItemPlacements | None = _field(default=None)
    """Места размещения"""


class UpdateAuctionPlacementPlacementsItemPlacements(WBModel):
    """Места размещения"""

    recommendations: bool | None = _field(default=None)
    """Размещение в рекомендациях:   - `false` — отключено   - `true` — включено"""
    search: bool | None = _field(default=None)
    """Размещение в поиске:   - `false` — отключено   - `true` — включено"""


class V0BidRecommendationBase(WBModel):
    """Рекомендуемые ставки для карточек товаров"""

    competitive_bid: V0BidRecommendationBaseBidCompetitiveBid | None = _field(
        default=None, name="competitiveBid"
    )
    leaders_bid: V0BidRecommendationBaseBidLeadersBid | None = _field(default=None, name="leadersBid")
    top2: V0BidRecommendationBaseBidTop2 | None = _field(default=None)


class V0BidRecommendationBaseBidCompetitiveBid(WBModel):
    """Конкурентная ставка — расчётная средняя ставка других продавцов, продающих аналогичные т"""

    bid_kopecks: int | None = _field(default=None, name="bidKopecks")
    """Рекомендуемая ставка в разменных единицах — 0,01 от базовой валюты аккаунта продавца"""


class V0BidRecommendationBaseBidLeadersBid(WBModel):
    """Лидерская ставка — средняя ставка с которой товары занимают лидирующие позиции в вашей к"""

    bid_kopecks: int | None = _field(default=None, name="bidKopecks")
    """Рекомендуемая ставка в разменных единицах — 0,01 от базовой валюты аккаунта продавца"""


class V0BidRecommendationBaseBidTop2(WBModel):
    """Топ-ставка"""

    bid_kopecks: int | None = _field(default=None, name="bidKopecks")
    """Рекомендуемая ставка в разменных единицах — 0,01 от базовой валюты аккаунта продавца. Если
    `0`, для данного предмета топ-ставка не используется
    """


class V0BidRecommendationNormQuery(WBModel):
    norm_query: str | None = _field(default=None, name="normQuery")
    """Поисковый кластер"""
    reach_max: V0BidRecommendationReachMax | None = _field(default=None, name="reachMax")
    reach_medium: V0BidRecommendationReachMedium | None = _field(default=None, name="reachMedium")
    reach_min: V0BidRecommendationReachMin | None = _field(default=None, name="reachMin")


class V0BidRecommendationReachMax(WBModel):
    """Максимальный охват: 76-100%"""

    bid_kopecks: int | None = _field(default=None, name="bidKopecks")
    """Рекомендуемая ставка в разменных единицах — 0,01 от базовой валюты аккаунта продавца."""
    bid_kopecks_min: int | None = _field(default=None, name="bidKopecksMin")
    """Минимальная ставка в разменных единицах — 0,01 от базовой валюты аккаунта продавца."""


class V0BidRecommendationReachMedium(WBModel):
    """Средний охват: 61-75%"""

    bid_kopecks: int | None = _field(default=None, name="bidKopecks")
    """Рекомендуемая ставка в разменных единицах — 0,01 от базовой валюты аккаунта продавца"""
    bid_kopecks_min: int | None = _field(default=None, name="bidKopecksMin")
    """Минимальная ставка в разменных единицах — 0,01 от базовой валюты аккаунта продавца"""


class V0BidRecommendationReachMin(WBModel):
    """Минимальный охват: 50-60%"""

    bid_kopecks: int | None = _field(default=None, name="bidKopecks")
    """Рекомендуемая ставка в разменных единицах — 0,01 от базовой валюты аккаунта продавца"""
    bid_kopecks_min: int | None = _field(default=None, name="bidKopecksMin")
    """Минимальная ставка в разменных единицах — 0,01 от базовой валюты аккаунта продавца"""


class V0BidsRecommendationsCpmResponse(WBModel):
    advert_id: int | None = _field(default=None, name="advertId")
    """ID кампании"""
    base: V0BidRecommendationBase | None = _field(default=None)
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""
    norm_queries: list[V0BidRecommendationNormQuery] | None = _field(default=None, name="normQueries")
    """Рекомендуемые ставки для поисковых кластеров"""
    payment_type: str | None = _field(default=None, name="paymentType")
    """Тип оплаты:   - `cpm` — за показы"""


class V0DeleteNormQueryBidsRequest(WBModel):
    bids: list[V0DeleteNormQueryBidsRequestItem] | None = _field(default=None)


class V0DeleteNormQueryBidsRequestItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    nm_id: int | None = _field(default=None)
    """Артикул WB"""
    norm_query: str | None = _field(default=None)
    """Поисковый кластер"""


class V0GetNormQueryBidsItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    bid: int | None = _field(default=None)
    """Текущая ставка в базовых единицах валюты аккаунта продавца за тысячу показов"""
    bid_kopecks: int | None = _field(default=None)
    """Текущая ставка в разменных единицах — 0,01 от базовой валюты аккаунта продавца за тысячу
    показов
    """
    currency: str | None = _field(default=None)
    """Валюта аккаунта продавца"""
    nm_id: int | None = _field(default=None)
    """Артикул WB"""
    norm_query: str | None = _field(default=None)
    """Поисковый кластер"""


class V0GetNormQueryBidsRequest(WBModel):
    items: list[V0GetNormQueryBidsRequestItem] | None = _field(default=None)


class V0GetNormQueryBidsRequestItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    nm_id: int | None = _field(default=None)
    """Артикул WB"""


class V0GetNormQueryBidsResponse(WBModel):
    bids: list[V0GetNormQueryBidsItem] | None = _field(default=None)


class V0GetNormQueryListRequest(WBModel):
    items: list[V0GetNormQueryListRequestItem] | None = _field(default=None)


class V0GetNormQueryListRequestItem(WBModel):
    advert_id: int | None = _field(default=None, name="advertId")
    """ID кампании"""
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""


class V0GetNormQueryListResponse(WBModel):
    items: list[V0GetNormQueryListResponseItem] | None = _field(default=None)


class V0GetNormQueryListResponseItem(WBModel):
    advert_id: int | None = _field(default=None, name="advertId")
    """ID кампании"""
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""
    norm_queries: V0GetNormQueryListResponseItemNormQueries | None = _field(default=None, name="normQueries")


class V0GetNormQueryListResponseItemNormQueries(WBModel):
    """Поисковые кластеры"""

    active: list[str] | None = _field(default=None)
    """Активные поисковые кластеры"""
    archived: list[str] | None = _field(default=None)
    """Архивные поисковые кластеры"""
    excluded: list[str] | None = _field(default=None)
    """Неактивные поисковые кластеры"""


class V0GetNormQueryMinusRequest(WBModel):
    items: list[V0GetNormQueryMinusRequestItem] | None = _field(default=None)


class V0GetNormQueryMinusRequestItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    nm_id: int | None = _field(default=None)
    """Артикул WB"""


class V0GetNormQueryMinusResponse(WBModel):
    items: list[V0GetNormQueryMinusResponseItem] | None = _field(default=None)


class V0GetNormQueryMinusResponseItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    nm_id: int | None = _field(default=None)
    """Артикул WB"""
    norm_queries: list[str] | None = _field(default=None)
    """Список минус-фраз"""


class V0GetNormQueryStatsItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    nm_id: int | None = _field(default=None)
    """Артикул WB"""
    stats: list[V0GetNormQueryStatsItemStat] | None = _field(default=None)


class V0GetNormQueryStatsItemStat(WBModel):
    atbs: int | None = _field(default=None)
    """Количество добавлений товаров в корзину"""
    avg_pos: float | None = _field(default=None)
    """Средняя позиция товара на страницах поисковой выдачи"""
    clicks: int | None = _field(default=None)
    """Количество кликов"""
    cpc: float | None = _field(default=None)
    """Стоимость одного клика в базовых единицах валюты аккаунта продавца"""
    cpm: float | None = _field(default=None)
    """Средняя стоимость за тысячу показов в базовых единицах валюты аккаунта продавца.  Для
    кампаний с типом оплаты `cpc` — за клики — значение будет `null`
    """
    ctr: float | None = _field(default=None)
    """Кликабельность — отношение числа кликов к количеству показов, %.  Для кампаний с типом
    оплаты `cpc` — за клики — значение будет `null`
    """
    currency: str | None = _field(default=None)
    """Валюта аккаунта продавца"""
    norm_query: str | None = _field(default=None)
    """Поисковый кластер"""
    orders: int | None = _field(default=None)
    """Количество заказов"""
    shks: int | None = _field(default=None)
    """Количество заказанных товаров, шт."""
    spend: float | None = _field(default=None)
    """Затраты на продвижение товаров в конкретном поисковом кластере кампании"""
    views: int | None = _field(default=None)
    """Количество просмотров.  Для кампаний с типом оплаты `cpc` — за клики — значение будет `null`
    """


class V0GetNormQueryStatsRequest(WBModel):
    from_: str | None = _field(default=None, name="from")
    """Дата начала периода"""
    items: list[V0GetNormQueryStatsRequestItemsItem] | None = _field(default=None)
    to: str | None = _field(default=None)
    """Дата окончания периода"""


class V0GetNormQueryStatsRequestItemsItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    nm_id: int | None = _field(default=None)
    """Артикул WB"""


class V0GetNormQueryStatsResponse(WBModel):
    """Статистика по поисковым кластерам"""

    stats: list[V0GetNormQueryStatsItem] | None = _field(default=None)


class V0SetMinusNormQueryRequest(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    nm_id: int | None = _field(default=None)
    """Артикул WB"""
    norm_queries: list[str] | None = _field(default=None)


class V0SetNormQueryBidsRequest(WBModel):
    bids: list[V0SetNormQueryBidsRequestItem] | None = _field(default=None)


class V0SetNormQueryBidsRequestItem(WBModel):
    advert_id: int | None = _field(default=None)
    """ID кампании"""
    bid: int | None = _field(default=None)
    """Ставка за тысячу показов в базовых единицах валюты аккаунта продавца"""
    nm_id: int | None = _field(default=None)
    """Артикул WB"""
    norm_query: str | None = _field(default=None)
    """Поисковый кластер"""


class V1GetNormQueryStatsRequest(WBModel):
    from_: str | None = _field(default=None, name="from")
    """Дата начала периода"""
    items: list[V1GetNormQueryStatsRequestItemsItem] | None = _field(default=None)
    to: str | None = _field(default=None)
    """Дата окончания периода периода"""


class V1GetNormQueryStatsRequestItemsItem(WBModel):
    advert_id: int | None = _field(default=None, name="advertId")
    """ID кампании"""
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""


class V1GetNormQueryStatsResponse(WBModel):
    items: list[V1GetNormQueryStatsResponseItem] | None = _field(default=None)


class V1GetNormQueryStatsResponseItem(WBModel):
    advert_id: int | None = _field(default=None, name="advertId")
    """ID кампании"""
    daily_stats: list[V1GetNormQueryStatsResponseItemDailyStat] | None = _field(
        default=None, name="dailyStats"
    )
    """Статистика с детализацией по дням"""
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""


class V1GetNormQueryStatsResponseItemDailyStat(WBModel):
    date: str | None = _field(default=None)
    """Дата"""
    stat: V1GetNormQueryStatsResponseItemStat | None = _field(default=None)


class V1GetNormQueryStatsResponseItemStat(WBModel):
    atbs: int | None = _field(default=None)
    """Количество добавлений товаров в корзину"""
    avg_pos: float | None = _field(default=None, name="avgPos")
    """Средняя позиция товара на страницах поисковой выдачи"""
    clicks: int | None = _field(default=None)
    """Количество кликов"""
    cpc: float | None = _field(default=None)
    """Средняя стоимость клика в базовых единицах валюты аккаунта продавца"""
    cpm: float | None = _field(default=None)
    """Средняя стоимость за тысячу показов в базовых единицах валюты аккаунта продавца.  Для
    кампаний с типом оплаты `cpc` — за клики — значение будет `null`
    """
    ctr: float | None = _field(default=None)
    """CTR (click-through rate) — отношение числа кликов к количеству показов в процентах.  Для
    кампаний с типом оплаты `cpc` — за клики — значение будет `null`
    """
    norm_query: str | None = _field(default=None, name="normQuery")
    """Поисковый кластер"""
    orders: int | None = _field(default=None)
    """Количество заказов"""
    shks: int | None = _field(default=None)
    """Количество заказанных товаров, шт."""
    spend: float | None = _field(default=None)
    """Затраты на продвижение товаров в конкретном поисковом кластере кампании"""
    views: int | None = _field(default=None)
    """Количество просмотров.  Для кампаний с типом оплаты `cpc` — за клики — значение будет `null`
    """


class V1SetNormQueryBidsRequest(WBModel):
    bids: list[V1SetNormQueryBidsRequestItem] | None = _field(default=None)


class V1SetNormQueryBidsRequestItem(WBModel):
    advert_id: int | None = _field(default=None, name="advertId")
    """ID кампании"""
    bid_minor_units: int | None = _field(default=None, name="bidMinorUnits")
    """Ставка в разменных единицах — 0,01 от базовой валюты аккаунта продавца. Допустимый шаг
    ставки указан в ответе метода GET /api/advert/v1/config
    """
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""
    norm_query: str | None = _field(default=None, name="normQuery")
    """Поисковый кластер"""


class V1SetNormQueryBidsResponse(WBModel):
    failed: list[NormQueryBidFailResponseItem] | None = _field(default=None)
    success: list[V1SetNormQueryBidsSuccessResponseItem] | None = _field(default=None)


class V1SetNormQueryBidsSuccessResponseItem(WBModel):
    advert_id: int | None = _field(default=None, name="advertId")
    """ID кампании"""
    currency: str | None = _field(default=None)
    """Валюта аккаунта продавца"""
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""
    norm_query: str | None = _field(default=None, name="normQuery")
    """Поисковый кластер — это группа похожих поисковых запросов, по которым покупатели находят
    товары
    """


class V2GetConfigResponse(WBModel):
    cpc_step: int | None = _field(default=None, name="cpcStep")
    """Шаг ставки в разменных единицах — 0,01 от базовой валюты аккаунта продавца для кампаний CPC
    """
    cpm_step: int | None = _field(default=None, name="cpmStep")
    """Шаг ставки в разменных единицах — 0,01 от базовой валюты аккаунта продавца для CPM-кампаний
    """
    currency: str | None = _field(default=None)
    """Валюта аккаунта продавца"""
    currency_code: int | None = _field(default=None, name="currencyCode")
    """Код валюты аккаунта продавца"""
    min_top_up: int | None = _field(default=None, name="minTopUp")
    """Минимальная сумма пополнения бюджета кампании в разменных единицах — 0,01 от базовой валюты
    аккаунта продавца. …
    """
