# @generated
# This file was auto-generated by scripts/codegen.py from specs/. Do not edit by hand.

from __future__ import annotations

from typing import Any

from msgspec import field as _field

from ..client.model import WBModel


class Chat(WBModel):
    chat_id: str | None = _field(default=None, name="chatID")
    """ID чата"""
    client_name: str | None = _field(default=None, name="clientName")
    """Имя покупателя"""
    good_card: Listing | None = _field(default=None, name="goodCard")
    """Информация о заказе"""
    last_message: ChatLastMessage | None = _field(default=None, name="lastMessage")
    """Последнее сообщение в чате"""
    reply_sign: str | None = _field(default=None, name="replySign")
    """Подпись чата. Требуется при отправке сообщения"""


class ChatLastMessage(WBModel):
    add_timestamp: int | None = _field(default=None, name="addTimestamp")
    """Время сообщения"""
    text: str | None = _field(default=None)
    """Текст сообщения"""


class ChatsResponse(WBModel):
    errors: list[str] | None = _field(default=None)
    """Ошибки, если есть"""
    result: list[Chat] | None = _field(default=None)


class CreateFeedbacksAnswerBody(WBModel):
    id: str | None = _field(default=None)
    """ID отзыва"""
    text: str | None = _field(default=None)
    """Текст ответа"""


class CreateFeedbacksOrderReturnsBody(WBModel):
    feedback_id: str | None = _field(default=None, name="feedbackId")
    """ID отзыва"""


class CreateFeedbacksOrderReturnsResponse(WBModel):
    additional_errors: list[str] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: dict[str, Any] | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Есть ли ошибка"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class DeleteFeedbacksPinResponse(WBModel):
    data: list[int] | None = _field(default=None)
    """Список `pinId` — ID операций закрепления отзывов, которые были успешно откреплены"""


class Event(WBModel):
    add_time: str | None = _field(default=None, name="addTime")
    """Время появления события на сервере в UTC"""
    add_timestamp: int | None = _field(default=None, name="addTimestamp")
    """Время появления события на сервере. Формат Unix timestamp"""
    chat_id: str | None = _field(default=None, name="chatID")
    """ID чата"""
    client_name: str | None = _field(default=None, name="clientName")
    """Имя покупателя"""
    event_id: str | None = _field(default=None, name="eventID")
    """ID события"""
    event_type: str | None = _field(default=None, name="eventType")
    """Тип события: - `message` — сообщение"""
    is_new_chat: bool | None = _field(default=None, name="isNewChat")
    """Признак нового чата: - `false` — чат не новый - `true` — чат новый"""
    message: EventMessage | None = _field(default=None)
    """Данные сообщения"""
    reply_sign: str | None = _field(default=None, name="replySign")
    """Подпись чата. Доступна только при `"isNewChat": true`. Требуется при отправке сообщения
    """
    sender: str | None = _field(default=None)
    """Отправитель: - `client` — покупатель - `seller` — продавец - `wb` — Wildberries"""
    source: str | None = _field(default=None)
    """Источник отправки сообщения: - `seller-portal` — портал продавцов - `seller-public-api` —
    API Чата с покупателями - `rusite` — портал покупателей …
    """


class EventAttachments(WBModel):
    """Вложения"""

    files: list[File] | None = _field(default=None)
    """Файлы"""
    good_card: Listing | None = _field(default=None, name="goodCard")
    """Информация о заказе"""
    images: list[Image] | None = _field(default=None)
    """Изображения"""


class EventMessage(WBModel):
    """Данные сообщения"""

    attachments: EventAttachments | None = _field(default=None)
    """Вложения"""
    text: str | None = _field(default=None)
    """Текст сообщения"""


class EventsResponse(WBModel):
    errors: list[str] | None = _field(default=None)
    """Ошибки, если есть"""
    result: EventsResult | None = _field(default=None)


class EventsResult(WBModel):
    events: list[Event] | None = _field(default=None)
    newest_event_time: str | None = _field(default=None, name="newestEventTime")
    """Время новейшего события в ответе"""
    next: int | None = _field(default=None)
    """Пагинатор. Значение поля необходимо указать в запросе для получения следующего пакета данных
    """
    oldest_event_time: str | None = _field(default=None, name="oldestEventTime")
    """Время старейшего события в ответе"""
    total_events: int | None = _field(default=None, name="totalEvents")
    """Количество событий"""


class File(WBModel):
    content_type: str | None = _field(default=None, name="contentType")
    """Тип файла"""
    date: str | None = _field(default=None)
    """Дата загрузки файла"""
    download_id: str | None = _field(default=None, name="downloadID")
    """ID файла. Получить файл"""
    name: str | None = _field(default=None)
    """Название файла"""
    size: int | None = _field(default=None)
    """Размер файла в байтах"""
    url: str | None = _field(default=None)
    """URL для получения файла"""


class GetFeedbackResponse(WBModel):
    additional_errors: list[str] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: GetFeedbackResponseData | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Есть ли ошибка"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetFeedbackResponseData(WBModel):
    answer: GetFeedbackResponseDataAnswer | None = _field(default=None)
    """Структура ответа"""
    bables: list[str] | None = _field(default=None)
    """Список тегов покупателя"""
    child_feedback_id: str | None = _field(default=None, name="childFeedbackId")
    """ID дополненного отзыва (`null`, если этот отзыв дополненный)"""
    color: str | None = _field(default=None)
    """Цвет товара"""
    cons: str | None = _field(default=None)
    """Недостатки товара"""
    created_date: str | None = _field(default=None, name="createdDate")
    """Дата и время создания отзыва"""
    id: str | None = _field(default=None)
    """ID отзыва"""
    is_able_return_product_orders: bool | None = _field(default=None, name="isAbleReturnProductOrders")
    """Опция возврата товара:   - `true` — доступна   - `false` — недоступна"""
    is_able_supplier_feedback_valuation: bool | None = _field(
        default=None, name="isAbleSupplierFeedbackValuation"
    )
    """Доступна ли продавцу возможность оставить жалобу на отзыв:   - `true`— да   - `false` — нет
    """
    is_able_supplier_product_valuation: bool | None = _field(
        default=None, name="isAbleSupplierProductValuation"
    )
    """Доступна ли продавцу возможность сообщить о проблеме с товаром  (`true` - доступна, `false`
    - не доступна)
    """
    last_order_created_at: str | None = _field(default=None, name="lastOrderCreatedAt")
    """Дата покупки"""
    last_order_shk_id: int | None = _field(default=None, name="lastOrderShkId")
    """Штрихкод единицы товара"""
    matching_size: str | None = _field(default=None, name="matchingSize")
    """Соответствие заявленного размера реальному. Возможные значения: - ` ` - для безразмерных
    товаров - `ок` - соответствует размеру - `smaller` - маломерит …
    """
    order_status: str | None = _field(default=None, name="orderStatus")
    """Статус заказа. Возможные значения: - `buyout` — выкуплен - `rejected` — отказались -
    `returned` — возврат - `notSpecified` — статус не присвоен
    """
    parent_feedback_id: str | None = _field(default=None, name="parentFeedbackId")
    """ID начального отзыва (`null`, если этот отзыв начальный)"""
    photo_links: list[GetFeedbackResponseDataPhotoLinksItem] | None = _field(default=None, name="photoLinks")
    """Массив структур фотографий"""
    product_details: GetFeedbackResponseDataProductDetails | None = _field(
        default=None, name="productDetails"
    )
    """Item information"""
    product_valuation: int | None = _field(default=None, name="productValuation")
    """Оценка товара"""
    pros: str | None = _field(default=None)
    """Достоинства товара"""
    return_product_orders_date: str | None = _field(default=None, name="returnProductOrdersDate")
    """Дата и время, когда на запрос возврата был получен ответ со статус-кодом 200."""
    state: str | None = _field(default=None)
    """Статус отзыва:   - `none` - не обработан (новый)   - `wbRu` - обработан"""
    subject_id: int | None = _field(default=None, name="subjectId")
    """ID предмета"""
    subject_name: str | None = _field(default=None, name="subjectName")
    """Название предмета"""
    supplier_feedback_valuation: int | None = _field(default=None, name="supplierFeedbackValuation")
    """Ключ причины жалобы на отзыв"""
    supplier_product_valuation: int | None = _field(default=None, name="supplierProductValuation")
    """Ключ проблемы с товаром"""
    text: str | None = _field(default=None)
    """Текст отзыва"""
    user_name: str | None = _field(default=None, name="userName")
    """Имя автора отзыва"""
    video: GetFeedbackResponseDataVideo | None = _field(default=None)
    """Структура видео"""
    was_viewed: bool | None = _field(default=None, name="wasViewed")
    """Просмотрен ли отзыв"""


class GetFeedbackResponseDataAnswer(WBModel):
    """Структура ответа"""

    editable: bool | None = _field(default=None)
    """Можно ли отредактировать ответ:   - `false` — нет   - `true` — да"""
    state: str | None = _field(default=None)
    """Статус:   - `none` — новый   - `wbRu`— отображается на сайте   - `reviewRequired` — ответ
    проходит проверку   - `rejected` — ответ отклонён
    """
    text: str | None = _field(default=None)
    """Текст ответа"""


class GetFeedbackResponseDataPhotoLinksItem(WBModel):
    full_size: str | None = _field(default=None, name="fullSize")
    """Адрес фотографии полного размера"""
    mini_size: str | None = _field(default=None, name="miniSize")
    """Адрес фотографии маленького размера"""


class GetFeedbackResponseDataProductDetails(WBModel):
    """Item information"""

    brand_name: str | None = _field(default=None, name="brandName")
    """Бренд товара"""
    imt_id: int | None = _field(default=None, name="imtId")
    """ID для объединённых карточек товаров"""
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""
    product_name: str | None = _field(default=None, name="productName")
    """Название товара"""
    size: str | None = _field(default=None)
    """Размер товара (`techSize` в КТ)"""
    supplier_article: str | None = _field(default=None, name="supplierArticle")
    """Артикул продавца"""
    supplier_name: str | None = _field(default=None, name="supplierName")
    """Имя продавца"""


class GetFeedbackResponseDataVideo(WBModel):
    """Структура видео"""

    duration_sec: int | None = _field(default=None, name="durationSec")
    """Общая продолжительность видео"""
    link: str | None = _field(default=None)
    """Ссылка на файл плейлиста видео (доступно по протоколу hls)"""
    preview_image: str | None = _field(default=None, name="previewImage")
    """Ссылка на обложку видео"""


class GetFeedbacksArchiveResponse(WBModel):
    additional_errors: list[str] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: GetFeedbacksArchiveResponseData | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Есть ли ошибка"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetFeedbacksArchiveResponseData(WBModel):
    feedbacks: list[GetFeedbacksArchiveResponseDataFeedbacksItem] | None = _field(default=None)
    """Массив отзывов"""


class GetFeedbacksArchiveResponseDataFeedbacksItem(WBModel):
    answer: GetFeedbacksArchiveResponseDataFeedbacksItemAnswer | None = _field(default=None)
    """Структура ответа"""
    bables: list[str] | None = _field(default=None)
    """Список тегов покупателя"""
    child_feedback_id: str | None = _field(default=None, name="childFeedbackId")
    """ID дополненного отзыва (`null`, если этот отзыв дополненный)"""
    color: str | None = _field(default=None)
    """Цвет товара"""
    cons: str | None = _field(default=None)
    """Недостатки товара"""
    created_date: str | None = _field(default=None, name="createdDate")
    """Дата и время создания отзыва"""
    id: str | None = _field(default=None)
    """ID отзыва"""
    is_able_return_product_orders: bool | None = _field(default=None, name="isAbleReturnProductOrders")
    """Опция возврата товара:  - `true` — доступна  - `false` — недоступна"""
    is_able_supplier_feedback_valuation: bool | None = _field(
        default=None, name="isAbleSupplierFeedbackValuation"
    )
    """Доступна ли продавцу возможность оставить жалобу на отзыв (`true` — доступна, `false` — не
    доступна)
    """
    is_able_supplier_product_valuation: bool | None = _field(
        default=None, name="isAbleSupplierProductValuation"
    )
    """Доступна ли продавцу возможность сообщить о проблеме с товаром:   - `true` — да   - `false`
    — нет
    """
    last_order_created_at: str | None = _field(default=None, name="lastOrderCreatedAt")
    """Дата покупки"""
    last_order_shk_id: int | None = _field(default=None, name="lastOrderShkId")
    """Штрихкод единицы товара"""
    matching_size: str | None = _field(default=None, name="matchingSize")
    """Соответствие заявленного размера реальному. Возможные значения: - ` ` — для безразмерных
    товаров - `ок` — соответствует размеру - `smaller` — маломерит …
    """
    order_status: str | None = _field(default=None, name="orderStatus")
    """Статус заказа. Возможные значения: - `buyout` — выкуплен - `rejected` — отказались -
    `returned` — возврат - `notSpecified` — статус не присвоен
    """
    parent_feedback_id: str | None = _field(default=None, name="parentFeedbackId")
    """ID начального отзыва (`null`, если этот отзыв начальный)"""
    photo_links: list[GetFeedbacksArchiveResponseDataFeedbacksItemPhotoLinksItem] | None = _field(
        default=None, name="photoLinks"
    )
    """Массив структур фотографий"""
    product_details: GetFeedbacksArchiveResponseDataFeedbacksItemProductDetails | None = _field(
        default=None, name="productDetails"
    )
    """Информация о товаре"""
    product_valuation: int | None = _field(default=None, name="productValuation")
    """Оценка товара"""
    pros: str | None = _field(default=None)
    """Достоинства товара"""
    return_product_orders_date: str | None = _field(default=None, name="returnProductOrdersDate")
    """Дата и время, когда на запрос возврата был получен ответ со статус-кодом 200."""
    state: str | None = _field(default=None)
    """Статус отзыва:   - `none` - не обработан (новый)   - `wbRu` - обработан"""
    subject_id: int | None = _field(default=None, name="subjectId")
    """ID предмета"""
    subject_name: str | None = _field(default=None, name="subjectName")
    """Название предмета"""
    supplier_feedback_valuation: int | None = _field(default=None, name="supplierFeedbackValuation")
    """Ключ причины жалобы на отзыв"""
    supplier_product_valuation: int | None = _field(default=None, name="supplierProductValuation")
    """Ключ проблемы с товаром"""
    text: str | None = _field(default=None)
    """Текст отзыва"""
    user_name: str | None = _field(default=None, name="userName")
    """Имя автора отзыва"""
    video: GetFeedbacksArchiveResponseDataFeedbacksItemVideo | None = _field(default=None)
    """Структура видео"""
    was_viewed: bool | None = _field(default=None, name="wasViewed")
    """Просмотрен ли отзыв"""


class GetFeedbacksArchiveResponseDataFeedbacksItemAnswer(WBModel):
    """Структура ответа"""

    editable: bool | None = _field(default=None)
    """Можно ли отредактировать ответ:   - `false` — нет   - `true` — да"""
    state: str | None = _field(default=None)
    """Статус:   - `none` — новый   - `wbRu` — отображается на сайте   - `reviewRequired` — ответ
    проходит проверку   - `rejected` — ответ отклонён
    """
    text: str | None = _field(default=None)
    """Текст ответа"""


class GetFeedbacksArchiveResponseDataFeedbacksItemPhotoLinksItem(WBModel):
    full_size: str | None = _field(default=None, name="fullSize")
    """Адрес фотографии полного размера"""
    mini_size: str | None = _field(default=None, name="miniSize")
    """Адрес фотографии маленького размера"""


class GetFeedbacksArchiveResponseDataFeedbacksItemProductDetails(WBModel):
    """Информация о товаре"""

    brand_name: str | None = _field(default=None, name="brandName")
    """Бренд товара"""
    imt_id: int | None = _field(default=None, name="imtId")
    """ID для объединённых карточек товаров"""
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""
    product_name: str | None = _field(default=None, name="productName")
    """Название товара"""
    size: str | None = _field(default=None)
    """Размер товара (`techSize` в КТ)"""
    supplier_article: str | None = _field(default=None, name="supplierArticle")
    """Артикул продавца"""
    supplier_name: str | None = _field(default=None, name="supplierName")
    """Имя продавца"""


class GetFeedbacksArchiveResponseDataFeedbacksItemVideo(WBModel):
    """Структура видео"""

    duration_sec: int | None = _field(default=None, name="durationSec")
    """Общая продолжительность видео"""
    link: str | None = _field(default=None)
    """Ссылка на файл плейлиста видео (доступно по протоколу HLS)"""
    preview_image: str | None = _field(default=None, name="previewImage")
    """Ссылка на обложку видео"""


class GetFeedbacksCountResponse(WBModel):
    additional_errors: list[str] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: int | None = _field(default=None)
    """Количество отзывов"""
    error: bool | None = _field(default=None)
    """Есть ли ошибка"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetFeedbacksCountUnansweredResponse(WBModel):
    additional_errors: list[str] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: GetFeedbacksCountUnansweredResponseData | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Есть ли ошибка"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetFeedbacksCountUnansweredResponseData(WBModel):
    count_unanswered: int | None = _field(default=None, name="countUnanswered")
    """Количество необработанных отзывов"""
    count_unanswered_today: int | None = _field(default=None, name="countUnansweredToday")
    """Количество необработанных отзывов за сегодня"""


class GetFeedbacksPinsCountResponse(WBModel):
    data: int | None = _field(default=None)
    """Количество отзывов"""


class GetFeedbacksPinsLimitsResponse(WBModel):
    data: GetFeedbacksPinsLimitsResponseData | None = _field(default=None)


class GetFeedbacksPinsLimitsResponseData(WBModel):
    subscription: GetFeedbacksPinsLimitsResponseDataSubscription | None = _field(default=None)
    """Лимиты по подписке"""
    tariff: GetFeedbacksPinsLimitsResponseDataTariff | None = _field(default=None)
    """Лимиты по тарифной опции"""


class GetFeedbacksPinsLimitsResponseDataSubscription(WBModel):
    per_unit_limit: int | None = _field(default=None, name="perUnitLimit")
    """Максимальное количество закреплённых отзывов в одной карточке товара или в группе
    объединённых карточек
    """
    remaining: int | None = _field(default=None)
    """Сколько ещё отзывов можно закрепить"""
    total_limit: int | None = _field(default=None, name="totalLimit")
    """Общий лимит закреплений"""
    unlimited: bool | None = _field(default=None)
    """Количество закреплённых отзывов не ограничено:   - `true` — да   - `false` — нет"""
    used: int | None = _field(default=None)
    """Текущее количество закреплённых отзывов"""


class GetFeedbacksPinsLimitsResponseDataTariff(WBModel):
    per_unit_limit: int | None = _field(default=None, name="perUnitLimit")
    """Максимальное количество закреплённых отзывов в одной карточке товара или в группе
    объединённых карточек
    """
    remaining: int | None = _field(default=None)
    """Сколько ещё отзывов можно закрепить"""
    total_limit: int | None = _field(default=None, name="totalLimit")
    """Общий лимит закреплений"""
    unlimited: bool | None = _field(default=None)
    """Количество закреплённых отзывов не ограничено:   - `true` — да   - `false` — нет"""
    used: int | None = _field(default=None)
    """Текущее количество закреплённых отзывов"""


class GetFeedbacksPinsResponse(WBModel):
    data: list[OpenapiPinnedReviewItemResult] | None = _field(default=None)
    next: int | None = _field(default=None)
    """Параметр пагинации. Укажите это значение в запросе, чтобы получить следующий пакет данных.
    Если поле отсутствует, вы получили все данные
    """


class GetFeedbacksResponse(WBModel):
    additional_errors: list[str] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: GetFeedbacksResponseData | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Есть ли ошибка"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetFeedbacksResponseData(WBModel):
    count_archive: int | None = _field(default=None, name="countArchive")
    """Количество обработанных отзывов"""
    count_unanswered: int | None = _field(default=None, name="countUnanswered")
    """Количество необработанных отзывов"""
    feedbacks: list[GetFeedbacksResponseDataFeedbacksItem] | None = _field(default=None)
    """Массив отзывов"""


class GetFeedbacksResponseDataFeedbacksItem(WBModel):
    answer: GetFeedbacksResponseDataFeedbacksItemAnswer | None = _field(default=None)
    """Структура ответа"""
    bables: list[str] | None = _field(default=None)
    """Список тегов покупателя"""
    child_feedback_id: str | None = _field(default=None, name="childFeedbackId")
    """ID дополненного отзыва (`null`, если этот отзыв дополненный)"""
    color: str | None = _field(default=None)
    """Цвет товара"""
    cons: str | None = _field(default=None)
    """Недостатки товара"""
    created_date: str | None = _field(default=None, name="createdDate")
    """Дата и время создания отзыва"""
    id: str | None = _field(default=None)
    """ID отзыва"""
    is_able_return_product_orders: bool | None = _field(default=None, name="isAbleReturnProductOrders")
    """Опция возврата товара:  - `true` — доступна  - `false` — недоступна"""
    is_able_supplier_feedback_valuation: bool | None = _field(
        default=None, name="isAbleSupplierFeedbackValuation"
    )
    """Доступна ли продавцу возможность оставить жалобу на отзыв (`true` — доступна, `false` — не
    доступна)
    """
    is_able_supplier_product_valuation: bool | None = _field(
        default=None, name="isAbleSupplierProductValuation"
    )
    """Доступна ли продавцу возможность сообщить о проблеме с товаром:   - `true` — да   - `false`
    — нет
    """
    last_order_created_at: str | None = _field(default=None, name="lastOrderCreatedAt")
    """Дата покупки"""
    last_order_shk_id: int | None = _field(default=None, name="lastOrderShkId")
    """Штрихкод единицы товара"""
    matching_size: str | None = _field(default=None, name="matchingSize")
    """Соответствие заявленного размера реальному. Возможные значения: - ` ` — для безразмерных
    товаров - `ок` — соответствует размеру - `smaller` — маломерит …
    """
    order_status: str | None = _field(default=None, name="orderStatus")
    """Статус заказа. Возможные значения: - `buyout` — выкуплен - `rejected` — отказались -
    `returned` — возврат - `notSpecified` — статус не присвоен
    """
    parent_feedback_id: str | None = _field(default=None, name="parentFeedbackId")
    """ID начального отзыва (`null`, если этот отзыв начальный)"""
    photo_links: list[GetFeedbacksResponseDataFeedbacksItemPhotoLinksItem] | None = _field(
        default=None, name="photoLinks"
    )
    """Массив структур фотографий"""
    product_details: GetFeedbacksResponseDataFeedbacksItemProductDetails | None = _field(
        default=None, name="productDetails"
    )
    """Информация о товаре"""
    product_valuation: int | None = _field(default=None, name="productValuation")
    """Оценка товара"""
    pros: str | None = _field(default=None)
    """Достоинства товара"""
    return_product_orders_date: str | None = _field(default=None, name="returnProductOrdersDate")
    """Дата и время, когда на запрос возврата был получен ответ со статус-кодом 200."""
    state: str | None = _field(default=None)
    """Статус отзыва:   - `none` - не обработан (новый)   - `wbRu` - обработан"""
    subject_id: int | None = _field(default=None, name="subjectId")
    """ID предмета"""
    subject_name: str | None = _field(default=None, name="subjectName")
    """Название предмета"""
    supplier_feedback_valuation: int | None = _field(default=None, name="supplierFeedbackValuation")
    """Ключ причины жалобы на отзыв"""
    supplier_product_valuation: int | None = _field(default=None, name="supplierProductValuation")
    """Ключ проблемы с товаром"""
    text: str | None = _field(default=None)
    """Текст отзыва"""
    user_name: str | None = _field(default=None, name="userName")
    """Имя автора отзыва"""
    video: GetFeedbacksResponseDataFeedbacksItemVideo | None = _field(default=None)
    """Структура видео"""
    was_viewed: bool | None = _field(default=None, name="wasViewed")
    """Просмотрен ли отзыв"""


class GetFeedbacksResponseDataFeedbacksItemAnswer(WBModel):
    """Структура ответа"""

    editable: bool | None = _field(default=None)
    """Можно ли отредактировать ответ:   - `false` — нет   - `true` — да"""
    state: str | None = _field(default=None)
    """Статус:   - `none` — новый   - `wbRu` — отображается на сайте   - `reviewRequired` — ответ
    проходит проверку   - `rejected` — ответ отклонён
    """
    text: str | None = _field(default=None)
    """Текст ответа"""


class GetFeedbacksResponseDataFeedbacksItemPhotoLinksItem(WBModel):
    full_size: str | None = _field(default=None, name="fullSize")
    """Адрес фотографии полного размера"""
    mini_size: str | None = _field(default=None, name="miniSize")
    """Адрес фотографии маленького размера"""


class GetFeedbacksResponseDataFeedbacksItemProductDetails(WBModel):
    """Информация о товаре"""

    brand_name: str | None = _field(default=None, name="brandName")
    """Бренд товара"""
    imt_id: int | None = _field(default=None, name="imtId")
    """ID для объединённых карточек товаров"""
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""
    product_name: str | None = _field(default=None, name="productName")
    """Название товара"""
    size: str | None = _field(default=None)
    """Размер товара (`techSize` в КТ)"""
    supplier_article: str | None = _field(default=None, name="supplierArticle")
    """Артикул продавца"""
    supplier_name: str | None = _field(default=None, name="supplierName")
    """Имя продавца"""


class GetFeedbacksResponseDataFeedbacksItemVideo(WBModel):
    """Структура видео"""

    duration_sec: int | None = _field(default=None, name="durationSec")
    """Общая продолжительность видео"""
    link: str | None = _field(default=None)
    """Ссылка на файл плейлиста видео (доступно по протоколу HLS)"""
    preview_image: str | None = _field(default=None, name="previewImage")
    """Ссылка на обложку видео"""


class GetNewFeedbacksQuestionsResponse(WBModel):
    additional_errors: list[str] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: GetNewFeedbacksQuestionsResponseData | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Есть ли ошибка"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetNewFeedbacksQuestionsResponseData(WBModel):
    has_new_feedbacks: bool | None = _field(default=None, name="hasNewFeedbacks")
    """Есть ли непросмотренные отзывы:  - `true` — да  - `false` — нет"""
    has_new_questions: bool | None = _field(default=None, name="hasNewQuestions")
    """Есть ли непросмотренные вопросы:    - `true` — да    - `false` — нет"""


class GetQuestionResponse(WBModel):
    additional_errors: list[str] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: GetQuestionResponseData | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Есть ли ошибка"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetQuestionResponseData(WBModel):
    answer: GetQuestionResponseDataAnswer | None = _field(default=None)
    """Ответ"""
    created_date: str | None = _field(default=None, name="createdDate")
    """Дата и время создания вопроса"""
    id: str | None = _field(default=None)
    """ID вопроса"""
    is_warned: bool | None = _field(default=None, name="isWarned")
    """Признак подозрительного вопроса. Если `true`, то вопрос опубликован, но на портале продавцов
    вы увидите баннер **Сообщение подозрительное**
    """
    product_details: GetQuestionResponseDataProductDetails | None = _field(
        default=None, name="productDetails"
    )
    """Item information"""
    state: str | None = _field(default=None)
    """Статус вопроса:   - `none` - вопрос отклонён продавцом (такой вопрос не отображается на
    портале покупателей) …
    """
    text: str | None = _field(default=None)
    """Текст вопроса"""
    was_viewed: bool | None = _field(default=None, name="wasViewed")
    """Просмотрен ли вопрос"""


class GetQuestionResponseDataAnswer(WBModel):
    """Ответ"""

    create_date: str | None = _field(default=None, name="createDate")
    """Дата и время создания ответа"""
    editable: bool | None = _field(default=None)
    """Можно ли отредактировать ответ (`false` - нельзя, `true` - можно)"""
    text: str | None = _field(default=None)
    """Текст ответа"""


class GetQuestionResponseDataProductDetails(WBModel):
    """Item information"""

    brand_name: str | None = _field(default=None, name="brandName")
    """Название бренда"""
    imt_id: int | None = _field(default=None, name="imtId")
    """ID для объединённых карточек товаров"""
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""
    product_name: str | None = _field(default=None, name="productName")
    """Название товара"""
    supplier_article: str | None = _field(default=None, name="supplierArticle")
    """Артикул продавца"""
    supplier_name: str | None = _field(default=None, name="supplierName")
    """Имя продавца"""


class GetQuestionsCountResponse(WBModel):
    additional_errors: list[str] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: int | None = _field(default=None)
    """Количество вопросов"""
    error: bool | None = _field(default=None)
    """Есть ли ошибка"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetQuestionsCountUnansweredResponse(WBModel):
    additional_errors: list[str] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: GetQuestionsCountUnansweredResponseData | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Есть ли ошибка"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetQuestionsCountUnansweredResponseData(WBModel):
    count_unanswered: int | None = _field(default=None, name="countUnanswered")
    """Количество неотвеченных вопросов"""
    count_unanswered_today: int | None = _field(default=None, name="countUnansweredToday")
    """Количество неотвеченных вопросов за сегодня"""


class GetQuestionsResponse(WBModel):
    additional_errors: list[str] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: GetQuestionsResponseData | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Есть ли ошибка"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""


class GetQuestionsResponseData(WBModel):
    count_archive: int | None = _field(default=None, name="countArchive")
    """Количество отвеченных вопросов"""
    count_unanswered: int | None = _field(default=None, name="countUnanswered")
    """Количество неотвеченных вопросов"""
    questions: list[GetQuestionsResponseDataQuestionsItem] | None = _field(default=None)
    """Вопросы"""


class GetQuestionsResponseDataQuestionsItem(WBModel):
    answer: GetQuestionsResponseDataQuestionsItemAnswer | None = _field(default=None)
    """Структура ответа"""
    created_date: str | None = _field(default=None, name="createdDate")
    """Дата и время создания вопроса"""
    id: str | None = _field(default=None)
    """id вопроса"""
    is_warned: bool | None = _field(default=None, name="isWarned")
    """Признак подозрительного вопроса. Если `true`, то вопрос опубликован, но на портале продавцов
    вы увидите баннер **Сообщение подозрительное**
    """
    product_details: GetQuestionsResponseDataQuestionsItemProductDetails | None = _field(
        default=None, name="productDetails"
    )
    """Информация о товаре"""
    state: str | None = _field(default=None)
    """Статус вопроса:   - `none` — вопрос отклонён продавцом (такой вопрос не отображается на
    портале покупателей) …
    """
    text: str | None = _field(default=None)
    """Текст вопроса"""
    was_viewed: bool | None = _field(default=None, name="wasViewed")
    """Просмотрен ли вопрос"""


class GetQuestionsResponseDataQuestionsItemAnswer(WBModel):
    """Структура ответа"""

    create_date: str | None = _field(default=None, name="createDate")
    """Дата и время создания ответа"""
    editable: bool | None = _field(default=None)
    """Можно ли отредактировать ответ (`false` - нельзя, `true` - можно)"""
    text: str | None = _field(default=None)
    """Текст ответа"""


class GetQuestionsResponseDataQuestionsItemProductDetails(WBModel):
    """Информация о товаре"""

    brand_name: str | None = _field(default=None, name="brandName")
    """Название бренда"""
    imt_id: int | None = _field(default=None, name="imtId")
    """ID для объединённых карточек товаров"""
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""
    product_name: str | None = _field(default=None, name="productName")
    """Название товара"""
    supplier_article: str | None = _field(default=None, name="supplierArticle")
    """Артикул продавца"""
    supplier_name: str | None = _field(default=None, name="supplierName")
    """Имя продавца"""


class Image(WBModel):
    """Изображение"""

    date: str | None = _field(default=None)
    """Дата загрузки изображения"""
    download_id: str | None = _field(default=None, name="downloadID")
    """ID файла. Получить файл"""
    url: str | None = _field(default=None)
    """URL для получения изображения"""


class Listing(WBModel):
    """Информация о заказе"""

    nm_id: int | None = _field(default=None, name="nmID")
    """Артикул WB"""
    price: int | None = _field(default=None)
    """Фактическая цена с учетом всех скидок. Взимается с покупателя"""
    price_currency: str | None = _field(default=None, name="priceCurrency")
    """Валюта"""
    rid: str | None = _field(default=None)
    """Уникальный ID заказа. Примечание: `rid` — это `srid` в ответах методов:   - Заявки
    покупателей на возврат   - Лента заказов   - Заказы   - Продажи …
    """
    size: str | None = _field(default=None)
    """Размер товара, соответствует `wbSize` в карточке товара"""


class MessageResponse(WBModel):
    errors: list[str] | None = _field(default=None)
    """Ошибки загрузки файлов, если есть"""
    result: MessageResponseResult | None = _field(default=None)


class MessageResponseResult(WBModel):
    add_time: int | None = _field(default=None, name="addTime")
    """Дата и время создания чата"""
    chat_id: str | None = _field(default=None, name="chatID")
    """ID чата"""
    sign: str | None = _field(default=None)
    """Подпись чата"""


class OpenapiPinReviewItem(WBModel):
    feedback_id: str | None = _field(default=None, name="feedbackId")
    """ID отзыва"""
    pin_method: str | None = _field(default=None, name="pinMethod")
    """Метод закрепления:   - `subscription` — подписка Джем   - `tariff` — тарифная опция"""
    pin_on: str | None = _field(default=None, name="pinOn")
    """Место закрепления отзыва:   - `nm` — карточка товара   - `imt` — группа объединённых
    карточек товаров
    """


class OpenapiPinnedReviewItemResult(WBModel):
    change_state_at: str | None = _field(default=None, name="changeStateAt")
    """Дата и время закрепления или открепления"""
    feedback_id: str | None = _field(default=None, name="feedbackId")
    """ID отзыва"""
    imt_id: int | None = _field(default=None, name="imtId")
    """ID для объединённых карточек товаров"""
    nm_id: int | None = _field(default=None, name="nmId")
    """Артикул WB"""
    pin_id: int | None = _field(default=None, name="pinId")
    """ID операции закрепления отзыва"""
    pin_method: str | None = _field(default=None, name="pinMethod")
    """Метод закрепления:   - `subscription` — подписка Джем   - `tariff` — тарифная опция"""
    pin_on: str | None = _field(default=None, name="pinOn")
    """Место закрепления отзыва:   - `nm` — карточка товара   - `imt` — группа объединённых
    карточек товаров
    """
    state: str | None = _field(default=None)
    """Закреплён ли отзыв:   - `pinned` — да   - `unpinned` — нет"""
    unpinned_cause: str | None = _field(default=None, name="unpinnedCause")
    """Причина открепления отзыва:   - `sysTariffUnpinned` — закончилась подписка или тарифная
    опция   - `sysLimitReached` — закончился общий лимит по подписке …
    """


class OpenapiResultErr(WBModel):
    detail: str | None = _field(default=None)
    """Детали ошибки"""
    origin: str | None = _field(default=None)
    """ID внутреннего сервиса WB"""
    request_id: str | None = _field(default=None, name="requestId")
    """ID запроса"""
    status: str | None = _field(default=None)
    """Статус"""
    title: str | None = _field(default=None)
    """Заголовок ошибки"""


class SetFeedbacksPinResponse(WBModel):
    data: list[SetFeedbacksPinResponseDataItem] | None = _field(default=None)


class SetFeedbacksPinResponseDataItem(WBModel):
    errors: list[OpenapiResultErr] | None = _field(default=None)
    """Детали ошибок"""
    feedback_id: str | None = _field(default=None, name="feedbackId")
    """ID отзыва"""
    is_errors: bool | None = _field(default=None, name="isErrors")
    """Есть ли ошибки"""
    pin_id: int | None = _field(default=None, name="pinId")
    """ID операции закрепления. Если поле отсутствует — закрепить отзыв не удалось"""
    pin_method: str | None = _field(default=None, name="pinMethod")
    """Метод закрепления:   - `subscription` — подписка Джем   - `tariff` — тарифная опция"""
    pin_on: str | None = _field(default=None, name="pinOn")
    """Место закрепления отзыва:   - `nm` — карточка товара   - `imt` — группа объединённых
    карточек товаров
    """


class UpdateFeedbacksAnswerBody(WBModel):
    id: str | None = _field(default=None)
    """ID отзыва"""
    text: str | None = _field(default=None)
    """Текст ответа"""


class UpdateQuestionBody(WBModel):
    id: str | None = _field(default=None)
    """Id вопроса"""
    was_viewed: bool | None = _field(default=None, name="wasViewed")
    """Просмотрен ли вопрос"""


class UpdateQuestionResponse(WBModel):
    additional_errors: list[str] | None = _field(default=None, name="additionalErrors")
    """Дополнительные ошибки"""
    data: dict[str, Any] | None = _field(default=None)
    error: bool | None = _field(default=None)
    """Есть ли ошибка"""
    error_text: str | None = _field(default=None, name="errorText")
    """Описание ошибки"""
