# @generated
# This file was auto-generated by scripts/codegen.py from specs/. Do not edit by hand.

from __future__ import annotations

from ..client.method import WBMethod
from ..utils.token import Scope
from .models import (
    ApiMetaDeleteResponses,
    ApiOrdersMetaDetailsResponse,
    ApiSGTINs,
    ApiStatusSetResponses,
    ClientInfoResp,
    DeliveryDatesInfoResp,
    GetDbwOrdersResponse,
    GetOrdersNewResponse,
    GetOrdersStatusResponse,
    GetOrdersStickersResponse,
    OrderCourierInfoResp,
)


class CancelDbwOrder(WBMethod[None]):
    """Отменить сборочное задание

    PATCH /api/v3/dbw/orders/{orderId}/cancel
    """

    __path__ = "/api/v3/dbw/orders/{orderId}/cancel"
    __http_method__ = "PATCH"
    __returns__ = None
    __path_params__ = ("orderId",)
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {
        "personal": (4000, 20),
        "service": (4000, 20),
        "basic_secret": (4000, 20),
        "basic": (360000, 1),
    }

    order_id: str | int
    """ID сборочного задания"""


class DeleteOrdersMeta(WBMethod[ApiMetaDeleteResponses]):
    """Удалить идентификаторы маркировки сборочных заданий

    POST /api/marketplace/v3/dbw/orders/meta/delete
    """

    __path__ = "/api/marketplace/v3/dbw/orders/meta/delete"
    __http_method__ = "POST"
    __returns__ = ApiMetaDeleteResponses
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {"all": (4000, 20)}
    __body_fields__ = {"key": "key", "orders_ids": "ordersIds"}

    key: str
    """Название идентификатора маркировки для удаления. Передаётся только одно значение"""
    orders_ids: list[int]
    """Список ID сборочных заданий"""


class GetDbwOrders(WBMethod[GetDbwOrdersResponse]):
    """Получить информацию о завершенных сборочных заданиях

    GET /api/v3/dbw/orders
    """

    __path__ = "/api/v3/dbw/orders"
    __http_method__ = "GET"
    __returns__ = GetDbwOrdersResponse
    __query_params__ = {"limit": "limit", "next_": "next", "date_from": "dateFrom", "date_to": "dateTo"}
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {"all": (4000, 20)}
    __paginate__ = "next"
    __items__ = "orders"

    date_from: int
    """Дата начала периода в формате Unix timestamp"""
    date_to: int
    """Дата конца периода в формате Unix timestamp"""
    limit: int
    """Параметр пагинации. Устанавливает предельное количество возвращаемых данных"""
    next_: int
    """Параметр пагинации. Устанавливает значение, с которого надо получить следующий пакет данных.
    Для получения полного списка данных должен быть равен `0` в первом …
    """


class GetOrdersClient(WBMethod[ClientInfoResp]):
    """Информация о покупателе

    POST /api/marketplace/v3/dbw/orders/client
    """

    __path__ = "/api/marketplace/v3/dbw/orders/client"
    __http_method__ = "POST"
    __returns__ = ClientInfoResp
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {"all": (4000, 20)}
    __items__ = "orders"
    __body_fields__ = {"orders": "orders"}

    orders: list[int] | None = None
    """Список ID сборочных заданий"""


class GetOrdersCourier(WBMethod[OrderCourierInfoResp]):
    """Информация о курьере

    POST /api/v3/dbw/orders/courier
    """

    __path__ = "/api/v3/dbw/orders/courier"
    __http_method__ = "POST"
    __returns__ = OrderCourierInfoResp
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {"all": (4000, 20)}
    __items__ = "orders"
    __body_fields__ = {"orders": "orders"}

    orders: list[int] | None = None
    """Список ID сборочных заданий"""


class GetOrdersDeliveryDate(WBMethod[DeliveryDatesInfoResp]):
    """Получить дату и время доставки

    POST /api/v3/dbw/orders/delivery-date
    """

    __path__ = "/api/v3/dbw/orders/delivery-date"
    __http_method__ = "POST"
    __returns__ = DeliveryDatesInfoResp
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {"all": (4000, 20)}
    __items__ = "orders"
    __body_fields__ = {"orders": "orders"}

    orders: list[int] | None = None
    """Список ID сборочных заданий"""


class GetOrdersMetaDetails(WBMethod[ApiOrdersMetaDetailsResponse]):
    """Получить идентификаторы маркировки сборочных заданий

    POST /api/marketplace/v3/dbw/orders/meta/details
    """

    __path__ = "/api/marketplace/v3/dbw/orders/meta/details"
    __http_method__ = "POST"
    __returns__ = ApiOrdersMetaDetailsResponse
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {"all": (4000, 20)}
    __items__ = "orders"
    __body_fields__ = {"orders_ids": "ordersIds"}

    orders_ids: list[int]
    """Список ID сборочных заданий"""


class GetOrdersNew(WBMethod[GetOrdersNewResponse]):
    """Получить список новых сборочных заданий

    GET /api/v3/dbw/orders/new
    """

    __path__ = "/api/v3/dbw/orders/new"
    __http_method__ = "GET"
    __returns__ = GetOrdersNewResponse
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {"all": (4000, 20)}
    __items__ = "orders"


class GetOrdersStatus(WBMethod[GetOrdersStatusResponse]):
    """Получить статусы сборочных заданий

    POST /api/v3/dbw/orders/status
    """

    __path__ = "/api/v3/dbw/orders/status"
    __http_method__ = "POST"
    __returns__ = GetOrdersStatusResponse
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {"all": (4000, 20)}
    __items__ = "orders"
    __body_fields__ = {"orders": "orders"}

    orders: list[int]
    """Список ID сборочных заданий"""


class GetOrdersStickers(WBMethod[GetOrdersStickersResponse]):
    """Получить стикеры сборочных заданий

    POST /api/v3/dbw/orders/stickers
    """

    __path__ = "/api/v3/dbw/orders/stickers"
    __http_method__ = "POST"
    __returns__ = GetOrdersStickersResponse
    __query_params__ = {"type_": "type", "width": "width", "height": "height"}
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {"all": (4000, 20)}
    __body_fields__ = {"orders": "orders"}

    height: int
    """Высота стикера"""
    type_: str
    """Тип стикера"""
    width: int
    """Ширина стикера"""
    orders: list[int] | None = None
    """Список ID сборочных заданий"""


class SetOrdersMetaGtin(WBMethod[None]):
    """Закрепить GTIN за сборочным заданием

    PUT /api/v3/dbw/orders/{orderId}/meta/gtin
    """

    __path__ = "/api/v3/dbw/orders/{orderId}/meta/gtin"
    __http_method__ = "PUT"
    __returns__ = None
    __path_params__ = ("orderId",)
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {"all": (1200, 20)}
    __body_fields__ = {"gtin": "gtin"}

    gtin: str
    """GTIN"""
    order_id: str | int
    """ID сборочного задания"""


class SetOrdersMetaImei(WBMethod[None]):
    """Закрепить IMEI за сборочным заданием

    PUT /api/v3/dbw/orders/{orderId}/meta/imei
    """

    __path__ = "/api/v3/dbw/orders/{orderId}/meta/imei"
    __http_method__ = "PUT"
    __returns__ = None
    __path_params__ = ("orderId",)
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {"all": (1200, 20)}
    __body_fields__ = {"imei": "imei"}

    imei: str
    """IMEI"""
    order_id: str | int
    """ID сборочного задания"""


class SetOrdersMetaSgtin(WBMethod[ApiStatusSetResponses]):
    """Закрепить коды маркировки Честного знака за сборочными заданиями

    POST /api/marketplace/v3/dbw/orders/meta/sgtin
    """

    __path__ = "/api/marketplace/v3/dbw/orders/meta/sgtin"
    __http_method__ = "POST"
    __returns__ = ApiStatusSetResponses
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {"all": (4000, 20)}
    __body_fields__ = {"orders": "orders"}

    orders: list[ApiSGTINs]


class SetOrdersMetaUin(WBMethod[None]):
    """Закрепить УИН за сборочным заданием

    PUT /api/v3/dbw/orders/{orderId}/meta/uin
    """

    __path__ = "/api/v3/dbw/orders/{orderId}/meta/uin"
    __http_method__ = "PUT"
    __returns__ = None
    __path_params__ = ("orderId",)
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {"all": (1200, 20)}
    __body_fields__ = {"uin": "uin"}

    order_id: str | int
    """ID сборочного задания"""
    uin: str
    """УИН"""


class UpdateOrdersConfirm(WBMethod[None]):
    """Перевести на сборку

    PATCH /api/v3/dbw/orders/{orderId}/confirm
    """

    __path__ = "/api/v3/dbw/orders/{orderId}/confirm"
    __http_method__ = "PATCH"
    __returns__ = None
    __path_params__ = ("orderId",)
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {"all": (4000, 20)}

    order_id: str | int
    """ID сборочного задания"""


class UpdateOrdersStatusDeliver(WBMethod[ApiStatusSetResponses]):
    """Перевести сборочные задания в доставку

    POST /api/marketplace/v3/dbw/orders/status/deliver
    """

    __path__ = "/api/marketplace/v3/dbw/orders/status/deliver"
    __http_method__ = "POST"
    __returns__ = ApiStatusSetResponses
    __scope__ = Scope.MARKETPLACE
    __host__ = "https://marketplace-api.wildberries.ru"
    __rate_limits__ = {"all": (4000, 20)}
    __body_fields__ = {"orders_ids": "ordersIds"}

    orders_ids: list[int]
    """Список ID сборочных заданий"""
