# @generated
# This file was auto-generated by scripts/codegen.py from specs/. Do not edit by hand.

from __future__ import annotations

from collections.abc import AsyncIterator
from typing import TYPE_CHECKING, Any

from .methods import (
    CancelOrdersStatus,
    CreateOrdersStatusReceive,
    CreateOrdersStatusReject,
    DeleteOrdersMeta,
    GetDbsGroups,
    GetDbsOrders,
    GetOrdersB2b,
    GetOrdersClient,
    GetOrdersDeliveryDate,
    GetOrdersFinalPrice,
    GetOrdersMetaDetails,
    GetOrdersNew,
    GetOrdersStatus,
    GetOrdersStickers,
    SetOrdersMetaCustomsDeclaration,
    SetOrdersMetaGtin,
    SetOrdersMetaImei,
    SetOrdersMetaSgtin,
    SetOrdersMetaUin,
    UpdateOrdersStatusConfirm,
    UpdateOrdersStatusDeliver,
)
from .models import (
    ApiB2bClientInfoResponses,
    ApiGTIN,
    ApiIMEI,
    ApiOrderCodeRequest,
    ApiOrdersFinalPriceResponse,
    ApiOrdersMetaDetailsResponse,
    ApiOrderStatusesV2,
    ApiSGTINs,
    ApiStatusSetDeliverResponses,
    ApiStatusSetResponses,
    ApiUIN,
    CreateOrdersStatusReceiveResponse,
    DbsOnlyClientInfoResp,
    DeliveryDatesInfoResp,
    GetDbsGroupsResponseItem,
    GetDbsOrdersResponse,
    GetOrdersNewResponse,
    GetOrdersStickersResponse,
    SetOrdersMetaCustomsDeclarationOrdersItem,
)


if TYPE_CHECKING:
    from ..client import WBApi


class OrdersDbs:
    """DBS.

    Узнать больше о модели DBS можно в справочном центре

    Управление сборочными заданиями и идентификаторами маркировки DBS (Delivery by Seller).

    Вы можете протестировать методы DBS в песочнице. Также в песочнице доступны специальные методы для
    эмуляции действий пользователя
    """

    __slots__ = ("_api",)

    def __init__(self, api: WBApi) -> None:
        self._api = api

    async def cancel_orders_status(self, *, orders_ids: list[int]) -> ApiStatusSetResponses:
        """Отменить сборочные задания

        :param orders_ids: Список ID сборочных заданий
        """
        return await CancelOrdersStatus(orders_ids=orders_ids).emit(self._api)

    async def create_orders_status_receive(
        self, *, orders: list[ApiOrderCodeRequest]
    ) -> CreateOrdersStatusReceiveResponse:
        """Сообщить о получении заказов"""
        return await CreateOrdersStatusReceive(orders=orders).emit(self._api)

    async def create_orders_status_reject(
        self, *, orders: list[ApiOrderCodeRequest]
    ) -> ApiStatusSetResponses:
        """Сообщить об отказе от заказов"""
        return await CreateOrdersStatusReject(orders=orders).emit(self._api)

    async def delete_orders_meta(self, *, key: str, order_ids: list[int]) -> ApiStatusSetResponses:
        """Удалить идентификаторы маркировки сборочных заданий

        :param key: Название идентификатора маркировки для удаления. Передаётся только одно значение
        :param order_ids: Список ID сборочных заданий
        """
        return await DeleteOrdersMeta(key=key, order_ids=order_ids).emit(self._api)

    async def get_dbs_groups(self, *, groups: list[str] | None = None) -> list[GetDbsGroupsResponseItem]:
        """Получить информацию о платной доставке

        :param groups: Список значений `groupId`. Можно получить из новых и завершенных сборочных заданий
        """
        return await GetDbsGroups(groups=groups).emit(self._api)

    async def get_dbs_orders(
        self, *, date_from: int, date_to: int, limit: int, next_: int, auto_paginate: bool = False
    ) -> GetDbsOrdersResponse | list[Any]:
        """Получить информацию о завершенных сборочных заданиях

        :param date_from: Дата начала периода в формате Unix timestamp
        :param date_to: Дата конца периода в формате Unix timestamp
        :param limit: Параметр пагинации. Устанавливает предельное количество возвращаемых данных.
        :param next_: Параметр пагинации. Устанавливает значение, с которого надо получить следующий пакет
            данных. Для получения полного списка данных должен быть равен `0` в первом …
        :param auto_paginate: автоматически собрать все страницы выборки
        """
        call = GetDbsOrders(date_from=date_from, date_to=date_to, limit=limit, next_=next_)
        return await call.paginate(self._api) if auto_paginate else await call.emit(self._api)

    async def iter_get_dbs_orders(
        self, *, date_from: int, date_to: int, limit: int, next_: int
    ) -> AsyncIterator[Any]:
        """Получить информацию о завершенных сборочных заданиях — постранично, по одной записи.

        :param date_from: Дата начала периода в формате Unix timestamp
        :param date_to: Дата конца периода в формате Unix timestamp
        :param limit: Параметр пагинации. Устанавливает предельное количество возвращаемых данных.
        :param next_: Параметр пагинации. Устанавливает значение, с которого надо получить следующий пакет
            данных. Для получения полного списка данных должен быть равен `0` в первом …
        """
        async for item in GetDbsOrders(date_from=date_from, date_to=date_to, limit=limit, next_=next_).stream(
            self._api
        ):
            yield item

    async def get_orders_b2b(self, *, orders_ids: list[int]) -> ApiB2bClientInfoResponses:
        """Информация о покупателе B2B

        :param orders_ids: Список ID сборочных заданий
        """
        return await GetOrdersB2b(orders_ids=orders_ids).emit(self._api)

    async def get_orders_client(self, *, orders: list[int] | None = None) -> DbsOnlyClientInfoResp:
        """Информация о покупателе

        :param orders: Список ID сборочных заданий
        """
        return await GetOrdersClient(orders=orders).emit(self._api)

    async def get_orders_delivery_date(self, *, orders: list[int] | None = None) -> DeliveryDatesInfoResp:
        """Получить дату и время доставки

        :param orders: Список ID сборочных заданий
        """
        return await GetOrdersDeliveryDate(orders=orders).emit(self._api)

    async def get_orders_final_price(self, *, orders: list[int] | None = None) -> ApiOrdersFinalPriceResponse:
        """Получить цены продавца и суммы к оплате

        :param orders: Список ID сборочных заданий
        """
        return await GetOrdersFinalPrice(orders=orders).emit(self._api)

    async def get_orders_meta_details(self, *, orders_ids: list[int]) -> ApiOrdersMetaDetailsResponse:
        """Получить идентификаторы маркировки сборочных заданий

        :param orders_ids: Список ID сборочных заданий
        """
        return await GetOrdersMetaDetails(orders_ids=orders_ids).emit(self._api)

    async def get_orders_new(self) -> GetOrdersNewResponse:
        """Получить список новых сборочных заданий"""
        return await GetOrdersNew().emit(self._api)

    async def get_orders_status(self, *, orders_ids: list[int]) -> ApiOrderStatusesV2:
        """Получить статусы сборочных заданий

        :param orders_ids: Список ID сборочных заданий
        """
        return await GetOrdersStatus(orders_ids=orders_ids).emit(self._api)

    async def get_orders_stickers(
        self, *, height: int, orders: list[int], type_: str, width: int
    ) -> GetOrdersStickersResponse:
        """Получить стикеры для сборочных заданий с доставкой в ПВЗ

        :param height: Высота стикера
        :param orders: Список ID сборочных заданий
        :param type_: Формат стикера
        :param width: Ширина стикера
        """
        return await GetOrdersStickers(height=height, orders=orders, type_=type_, width=width).emit(self._api)

    async def set_orders_meta_customs_declaration(
        self, *, orders: list[SetOrdersMetaCustomsDeclarationOrdersItem]
    ) -> ApiStatusSetResponses:
        """Закрепить номера ДТ за сборочными заданиями"""
        return await SetOrdersMetaCustomsDeclaration(orders=orders).emit(self._api)

    async def set_orders_meta_gtin(self, *, orders: list[ApiGTIN]) -> ApiStatusSetResponses:
        """Закрепить GTIN за сборочными заданиями"""
        return await SetOrdersMetaGtin(orders=orders).emit(self._api)

    async def set_orders_meta_imei(self, *, orders: list[ApiIMEI]) -> ApiStatusSetResponses:
        """Закрепить IMEI за сборочными заданиями"""
        return await SetOrdersMetaImei(orders=orders).emit(self._api)

    async def set_orders_meta_sgtin(self, *, orders: list[ApiSGTINs]) -> ApiStatusSetResponses:
        """Закрепить коды маркировки Честного знака за сборочными заданиями"""
        return await SetOrdersMetaSgtin(orders=orders).emit(self._api)

    async def set_orders_meta_uin(self, *, orders: list[ApiUIN]) -> ApiStatusSetResponses:
        """Закрепить УИН за сборочными заданиями"""
        return await SetOrdersMetaUin(orders=orders).emit(self._api)

    async def update_orders_status_confirm(self, *, orders_ids: list[int]) -> ApiStatusSetResponses:
        """Перевести сборочные задания на сборку

        :param orders_ids: Список ID сборочных заданий
        """
        return await UpdateOrdersStatusConfirm(orders_ids=orders_ids).emit(self._api)

    async def update_orders_status_deliver(self, *, orders_ids: list[int]) -> ApiStatusSetDeliverResponses:
        """Перевести сборочные задания в доставку

        :param orders_ids: Список ID сборочных заданий
        """
        return await UpdateOrdersStatusDeliver(orders_ids=orders_ids).emit(self._api)
