name: Tests

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/tests.yml"
      - "src/**"
      - "tests/**"
      - "pyproject.toml"

  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/tests.yml"
      - "src/**"
      - "tests/**"
      - "pyproject.toml"

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --all-extras

      - name: Run tests
        run: uv run pytest
